export interface NewsArticle {
  id: string;
  slug: string;
  title: string;
  description: string;
  content: string;
  category: string;
  categorySlug: string;
  categoryColor: string;
  image: string;
  author: string;
  publishedAt: string;
  isBreaking: boolean;
  isTrending: boolean;
  isFeatured: boolean;
  views: number;
  tags: string[];
  videoUrl?: string;
  districtSlug?: string;
}

export const categories = [
  { name: 'హోమ్', slug: 'home', color: '#02599c' },
  { name: 'తాజా వార్తలు', slug: 'latest', color: '#02599c' },
  { name: 'ఈ-పేపర్', slug: 'epaper', color: '#0f766e' },
  { name: 'రాజకీయాలు', slug: 'politics', color: '#1a6b3a' },
  { name: 'ఆంధ్రప్రదేశ్', slug: 'andhra-pradesh', color: '#d97706' },
  { name: 'తెలంగాణ', slug: 'telangana', color: '#7c3aed' },
  { name: 'జాతీయం', slug: 'national', color: '#0369a1' },
  { name: 'అంతర్జాతీయం', slug: 'international', color: '#0e7490' },
  { name: 'బిజినెస్', slug: 'business', color: '#15803d' },
  { name: 'సినిమా', slug: 'entertainment', color: '#db2777' },
  { name: 'క్రీడలు', slug: 'sports', color: '#ea580c' },
  { name: 'టెక్నాలజీ', slug: 'technology', color: '#4f46e5' },
  { name: 'ఆరోగ్యం', slug: 'health', color: '#0891b2' },
  { name: 'వైరల్', slug: 'viral', color: '#dc2626' },
  { name: 'లైఫ్ స్టైల్', slug: 'lifestyle', color: '#9333ea' },
  { name: 'రాశిఫలాలు', slug: 'rasipalalu', color: '#b45309' },
  { name: 'ఆల్బమ్‌లు', slug: 'photos', color: '#64748b' },
  { name: 'వీడియోలు', slug: 'videos', color: '#dc2626' },
  { name: 'వెబ్ స్టోరీస్', slug: 'webstories', color: '#ec4899' },
  { name: 'సంపాదకీయం', slug: 'sampadakiyam', color: '#be123c' },
  { name: 'సంపాదకీయం', slug: 'editorial', color: '#be123c' },
  { name: 'వైరల్ స్టోరీస్', slug: 'viral-stories', color: '#dc2626' },
  { name: 'మహిళలు', slug: 'women', color: '#ec4899' },
  { name: 'షార్ట్స్', slug: 'shorts', color: '#f43f5e' },
  { name: 'అంతర్మథనం', slug: 'antharmadanam', color: '#8b5cf6' },
  { name: 'మా బృందం (Team)', slug: 'team', color: '#4b5563' },
  { name: 'ఆధ్యాత్మికం', slug: 'adyathmikam', color: '#f59e0b' },
  { name: 'ఆధ్యాత్మికం', slug: 'devotional', color: '#f59e0b' },
];

export interface District {
  slug: string;
  name: string;
}

export const apDistricts: District[] = [
  { slug: 'alluri-sitharama-raju', name: 'అల్లూరి సీతారామరాజు' },
  { slug: 'anakapalli', name: 'అనకాపల్లి' },
  { slug: 'ananthapuram', name: 'అనంతపురం' },
  { slug: 'bapatla', name: 'బాపట్ల' },
  { slug: 'chittoor', name: 'చిత్తూరు' },
  { slug: 'east-godavari', name: 'తూర్పు గోదావరి' },
  { slug: 'eluru', name: 'ఏలూరు' },
  { slug: 'guntur', name: 'గుంటూరు' },
  { slug: 'kadapa', name: 'కడప' },
  { slug: 'konaseema', name: 'కోనసీమ' },
  { slug: 'krishna', name: 'కృష్ణా' },
  { slug: 'kurnool', name: 'కర్నూలు' },
  { slug: 'manyam', name: 'మన్యం' },
  { slug: 'nandyal', name: 'నంద్యాల' },
  { slug: 'nellore', name: 'నెల్లూరు' },
  { slug: 'ntr', name: 'ఎన్టీఆర్' },
  { slug: 'palnadu', name: 'పల్నాడు' },
  { slug: 'parvathipuram-manyam', name: 'పార్వతీపురం మన్యం' },
  { slug: 'prakasam', name: 'ప్రకాశం' },
  { slug: 'rajahmundry', name: 'రాజమండ్రి' },
  { slug: 'sri-sathya-sai', name: 'శ్రీ సత్యసాయి' },
  { slug: 'srikakulam', name: 'శ్రీకాకుళం' },
  { slug: 'tirupati', name: 'తిరుపతి' },
  { slug: 'visakhapatnam', name: 'విశాఖపట్నం' },
  { slug: 'vizianagaram', name: 'విజయనగరం' },
  { slug: 'west-godavari', name: 'పశ్చిమ గోదావరి' }
];

export const tgDistricts: District[] = [
  { slug: 'adilabad', name: 'ఆదిలాబాద్' },
  { slug: 'bhadradri-kothagudem', name: 'భద్రాద్రి కొత్తగూడెం' },
  { slug: 'hanmakonda', name: 'హన్మకొండ' },
  { slug: 'hyderabad', name: 'హైదరాబాద్' },
  { slug: 'jagtial', name: 'జగిత్యాల' },
  { slug: 'jangaon', name: 'జనగామ' },
  { slug: 'jayashankar-bhupalpally', name: 'జయశంకర్ భూపాలపల్లి' },
  { slug: 'jogulamba-gadwal', name: 'జోగులాంబ గద్వాల' },
  { slug: 'kamareddy', name: 'కామారెడ్డి' },
  { slug: 'karimnagar', name: 'కరీంనగర్' },
  { slug: 'khammam', name: 'ఖమ్మం' },
  { slug: 'kumuram-bheem-asifabad', name: 'కొమురం భీమ్ ఆసిఫాబాద్' },
  { slug: 'mahabubabad', name: 'మహబూబాబాద్' },
  { slug: 'mahabubnagar', name: 'మహబూబ్‌నగర్' },
  { slug: 'mancherial', name: 'మంచిర్యాల' },
  { slug: 'medak', name: 'మెదక్' },
  { slug: 'medchal-malkajgiri', name: 'మేడ్చల్ మల్కాజ్‌గిరి' },
  { slug: 'mulugu', name: 'ములుగు' },
  { slug: 'nagarkurnool', name: 'నాగర్‌కర్నూల్' },
  { slug: 'nalgonda', name: 'నల్గొండ' },
  { slug: 'narayanpet', name: 'నారాయణపేట్' },
  { slug: 'nirmal', name: 'నిర్మల్' },
  { slug: 'nizamabad', name: 'నిజామాబాద్' },
  { slug: 'peddapalli', name: 'పెద్దపల్లి' },
  { slug: 'rajanna-sircilla', name: 'రాజన్న సిరిసిల్ల' },
  { slug: 'rangareddy', name: 'రంగారెడ్డి' },
  { slug: 'sangareddy', name: 'సంగారెడ్డి' },
  { slug: 'siddipet', name: 'సిద్దిపేట' },
  { slug: 'suryapet', name: 'సూర్యాపేట' },
  { slug: 'vikarabad', name: 'వికారాబాద్' },
  { slug: 'wanaparthy', name: 'వనపర్తి' },
  { slug: 'warangal', name: 'వరంగల్' },
  { slug: 'yadadri-bhuvanagiri', name: 'యాదాద్రి భువనగిరి' }
];

export const districtNews: NewsArticle[] = [
  // Andhra Pradesh Districts
  {
    id: 'ap-dist-1',
    slug: 'visakhapatnam-it-hub-development',
    title: 'విశాఖపట్నంలో ఐటీ హబ్ అభివృద్ధికి ప్రత్యేక ప్రణాళిక - ముఖ్యమంత్రి',
    description: 'విశాఖపట్నం నగరాన్ని ఆంధ్రప్రదేశ్‌లోనే అతిపెద్ద ఐటీ హబ్‌గా తీర్చిదిద్దేందుకు ప్రభుత్వం కట్టుబడి ఉందని సీఎం ప్రకటించారు.',
    content: 'ఆంధ్రప్రదేశ్ ముఖ్యమంత్రి విశాఖపట్నంలో పర్యటించి పలు ఐటీ ప్రాజెక్టులకు శంకుస్థాపన చేశారు. రానున్న మూడేళ్లలో ఐటీ రంగంలో 50,000 ఉద్యోగాల కల్పనే లక్ష్యమని తెలిపారు.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&h=450&fit=crop',
    author: 'హై టీవీ రిపోర్టర్',
    publishedAt: '2026-06-05T08:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 12000,
    tags: ['విశాఖపట్నం', 'ఆంధ్రప్రదేశ్', 'ఐటీ హబ్'],
    districtSlug: 'visakhapatnam'
  },
  {
    id: 'ap-dist-2',
    slug: 'vijayawada-flyover-inauguration',
    title: 'విజయవాడలో కొత్తగా నిర్మించిన ఫ్లైఓవర్ ప్రారంభించిన మంత్రి',
    description: 'విజయవాడ నగరంలో ట్రాఫిక్ సమస్యల నివారణకు నూతన ఫ్లైఓవర్‌ను ఈరోజు రవాణా శాఖ మంత్రి ప్రారంభించారు.',
    content: 'ఈ ఫ్లైఓవర్ ప్రారంభంతో బెజవాడ ప్రజలకు ట్రాఫిక్ కష్టాలు చాలా వరకు తప్పుతాయని స్థానికులు హర్షం వ్యక్తం చేస్తున్నారు.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: '/vijayawada_flyover.png',
    author: 'హై టీవీ డెస్క్',
    publishedAt: '2026-06-05T07:15:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 15400,
    tags: ['విజయవాడ', 'ఆంధ్రప్రదేశ్', 'ఫ్లైఓవర్', 'ట్రాఫిక్'],
    districtSlug: 'vijayawada'
  },
  {
    id: 'ap-dist-3',
    slug: 'guntur-mirchi-yard-record-arrivals',
    title: 'గుంటూరు మిర్చి యార్డుకు రికార్డు స్థాయిలో తరలివచ్చిన పంట',
    description: 'ఆసియాలోనే అతిపెద్ద మిర్చి మార్కెట్ అయిన గుంటూరు యార్డుకు ఈరోజు రికార్డు స్థాయిలో మిర్చి బస్తాలు వచ్చాయి.',
    content: 'ధరలు ఆశాజనకంగా ఉండటంతో రైతులు పెద్ద సంఖ్యలో తమ పంటను విక్రయించేందుకు తరలివచ్చారు. అధికారులు తగిన ఏర్పాట్లు చేశారు.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&h=450&fit=crop',
    author: 'గుంటూరు ప్రతినిధి',
    publishedAt: '2026-06-05T06:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 9800,
    tags: ['గుంటూరు', 'ఆంధ్రప్రదేశ్', 'మిర్చి యార్డ్', 'రైతులు'],
    districtSlug: 'guntur'
  },
  {
    id: 'ap-dist-4',
    slug: 'tirupati-devotees-rush-increase',
    title: 'తిరుపతిలో పెరిగిన భక్తుల రద్దీ - ప్రత్యేక క్యూ లైన్లు ఏర్పాటు',
    description: 'వారాంతం కావడంతో తిరుమల శ్రీవారి దర్శనానికి భక్తులు పోటెత్తారు. కంపార్ట్‌మెంట్లు అన్నీ నిండిపోయాయి.',
    content: 'భక్తులకు ఎటువంటి ఇబ్బందులు కలగకుండా టీటీడీ అధికారులు నిరంతర పర్యవేక్షణ చేస్తున్నారు. అన్నప్రసాదం, పాలు నిరంతరం అందిస్తున్నారు.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: '/tirupati_devotees.png',
    author: 'తిరుమల ప్రతినిధి',
    publishedAt: '2026-06-05T05:45:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 18900,
    tags: ['తిరుపతి', 'ఆంధ్రప్రదేశ్', 'తిరుమల', 'భక్తులు'],
    districtSlug: 'tirupati'
  },
  {
    id: 'ap-dist-5',
    slug: 'nellore-paddy-cultivation-water',
    title: 'నెల్లూరు జిల్లాలో వరి సాగుకు పుష్కలంగా నీటి సరఫరా',
    description: 'నెల్లూరు జిల్లాలోని జలాశయాల నుంచి సాగునీరు విడుదల చేయడంతో రైతులు హర్షం వ్యక్తం చేస్తున్నారు.',
    content: 'ఈ సంవత్సరం విస్తారంగా వర్షాలు కురవడంతో నెల్లూరు జిల్లాలోని చెరువులు, కాలువలు జలకళను సంతరించుకున్నాయి.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=450&fit=crop',
    author: 'నెల్లూరు రిపోర్టర్',
    publishedAt: '2026-06-04T14:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 8700,
    tags: ['నెల్లూరు', 'ఆంధ్రప్రదేశ్', 'వ్యవసాయం', 'వరి సాగు'],
    districtSlug: 'nellore'
  },
  {
    id: 'ap-dist-6',
    slug: 'kurnool-highway-expansion-funds',
    title: 'కర్నూలులో హైవే విస్తరణ పనులు వేగవంతం - రూ. 800 కోట్ల నిధులు',
    description: 'కర్నూలు జిల్లా గుండా వెళ్లే జాతీయ రహదారిని 4 లేన్ల నుంచి 6 లేన్లుగా మార్చే పనులు జోరందుకున్నాయి.',
    content: 'కేంద్ర రవాణా మంత్రిత్వ శాఖ దీని కోసం రూ. 800 కోట్లను విడుదల చేసింది. ఈ పనులను 18 నెలల్లో పూర్తి చేయాలని లక్ష్యంగా పెట్టుకున్నారు.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=450&fit=crop',
    author: 'కర్నూలు డెస్క్',
    publishedAt: '2026-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 11200,
    tags: ['కర్నూలు', 'ఆంధ్రప్రదేశ్', 'రహదారి విస్తరణ'],
    districtSlug: 'kurnool'
  },
  {
    id: 'ap-dist-7',
    slug: 'kadapa-new-industries-mou',
    title: 'కడప జిల్లాలో కొత్త పరిశ్రమల స్థాపనకు ఒప్పందాలు',
    description: 'కడప జిల్లాలో పారిశ్రామికాభివృద్ధికి గాను పలు ప్రముఖ సంస్థలతో ప్రభుత్వం అవగాహన ఒప్పందాలు కుదుర్చుకుంది.',
    content: 'ఈ ఒప్పందాల ద్వారా జిల్లాలోని నిరుద్యోగ యువతకు పెద్ద ఎత్తున ఉపాధి అవకాశాలు లభించనున్నాయి.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=450&fit=crop',
    author: 'కడప బ్యూరో',
    publishedAt: '2026-06-04T10:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 9400,
    tags: ['కడప', 'ఆంధ్రప్రదేశ్', 'పరిశ్రమలు', 'ఉపాధి'],
    districtSlug: 'kadapa'
  },
  {
    id: 'ap-dist-8',
    slug: 'rajahmundry-godavari-ghat-tourism',
    title: 'రాజమండ్రి గోదావరి ఘాట్ వద్ద పర్యాటక ఉత్సవాలు ప్రారంభం',
    description: 'రాజమండ్రిలో గోదావరి హారతి ఘాట్ వద్ద మూడు రోజుల పాటు జరిగే సాంస్కృతిక ఉత్సవాలు వైభవంగా ప్రారంభమయ్యాయి.',
    content: 'పర్యాటకులను ఆకర్షించేందుకు లేజర్ షోలు, సంగీత కచేరీలు, నృత్య ప్రదర్శనలు ఏర్పాటు చేశారు.',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&h=450&fit=crop',
    author: 'రాజమండ్రి ప్రతినిధి',
    publishedAt: '2026-06-04T08:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 13500,
    tags: ['రాజమండ్రి', 'ఆంధ్రప్రదేశ్', 'గోదావరి', 'పర్యాటకం'],
    districtSlug: 'rajahmundry'
  },

  // Telangana Districts
  {
    id: 'tg-dist-1',
    slug: 'hyderabad-heavy-rain-traffic',
    title: 'హైదరాబాద్‌లో భారీ వర్షం - రోడ్లపై నిలిచిన ట్రాఫిక్',
    description: 'హైదరాబాద్ మహానగరంలో ఒక్కసారిగా కురిసిన భారీ వర్షానికి రోడ్లన్నీ జలమయమయ్యాయి. పలు చోట్ల కిలోమీటర్ల మేర ట్రాఫిక్ నిలిచింది.',
    content: 'నగరంలోని ఐటీ కారిడార్ తో పాటు దిల్ సుఖ్ నగర్, అమీర్ పేట ప్రాంతాలలో రహదారులు జలమయం కావడంతో వాహనదారులు తీవ్ర ఇబ్బందులు పడ్డారు.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&h=450&fit=crop',
    author: 'హైదరాబాద్ రిపోర్టర్',
    publishedAt: '2026-06-05T08:30:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 29800,
    tags: ['హైదరాబాద్', 'తెలంగాణ', 'వర్షం', 'ట్రాఫిక్'],
    districtSlug: 'hyderabad'
  },
  {
    id: 'tg-dist-2',
    slug: 'warangal-bhadrakali-temple-funds',
    title: 'వరంగల్ భద్రకాళి దేవాలయ అభివృద్ధికి రూ. 50 కోట్లు మంజూరు',
    description: 'వరంగల్‌లోని ప్రసిద్ధ భద్రకాళి క్షేత్ర పరిసరాల అభివృద్ధికి పర్యాటక శాఖ రూ. 50 కోట్ల నిధులను మంజూరు చేసింది.',
    content: 'దేవాలయ ప్రహరీ గోడల నిర్మాణం, భక్తుల కోసం వసతి గృహాలు, మరియు సుందరీకరణ పనులకు ఈ నిధులు వెచ్చించనున్నారు.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: '/warangal_temple.png',
    author: 'వరంగల్ ప్రతినిధి',
    publishedAt: '2026-06-05T07:15:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 11400,
    tags: ['వరంగల్', 'తెలంగాణ', 'భద్రకాళి దేవాలయం'],
    districtSlug: 'warangal'
  },
  {
    id: 'tg-dist-3',
    slug: 'nizamabad-turmeric-board-speed-up',
    title: 'నిజామాబాద్‌లో పసుపు బోర్డు ఏర్పాటు పనుల వేగవంతం',
    description: 'కేంద్ర ప్రభుత్వం నిజామాబాద్ జిల్లాలో పసుపు బోర్డు కార్యాలయ నిర్మాణ పనులను ముమ్మరం చేసింది.',
    content: 'పసుపు పండించే రైతులకు ఈ బోర్డు ద్వారా గిట్టుబాటు ధరతో పాటు ఎగుమతుల రంగంలో కూడా చక్కటి తోడ్పాటు లభిస్తుంది.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: '/turmeric_board.png',
    author: 'నిజామాబాద్ బ్యూరో',
    publishedAt: '2026-06-05T06:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 9200,
    tags: ['నిజామాబాద్', 'తెలంగాణ', 'పసుపు బోర్డు', 'రైతులు'],
    districtSlug: 'nizamabad'
  },
  {
    id: 'tg-dist-4',
    slug: 'karimnagar-cable-bridge-tourists',
    title: 'కరీంనగర్‌లో నిర్మిస్తున్న కేబుల్ బ్రిడ్జ్ సందర్శించిన పర్యాటకులు',
    description: 'కరీంనగర్ లోని మానేరు నదిపై నిర్మించిన ఐకానిక్ కేబుల్ బ్రిడ్జ్ సందర్శనకు సాయంత్రం వేళల్లో జనం తరలివస్తున్నారు.',
    content: 'లైటింగ్ మరియు లేజర్ షోలు ప్రత్యేక ఆకర్షణగా నిలుస్తుండటంతో స్థానిక పర్యాటక రంగం పుంజుకుంటోంది.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: '/karimnagar_bridge.png',
    author: 'కరీంనగర్ డెస్క్',
    publishedAt: '2026-06-05T05:45:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 14200,
    tags: ['కరీంనగర్', 'తెలంగాణ', 'కేబుల్ బ్రిడ్జ్', 'పర్యాటకం'],
    districtSlug: 'karimnagar'
  },
  {
    id: 'tg-dist-5',
    slug: 'khammam-agricultural-projects-inauguration',
    title: 'ఖమ్మం జిల్లాలో నూతన వ్యవసాయ ప్రాజెక్టులకు శంకుస్థాపన',
    description: 'ఖమ్మం జిల్లాలోని పలు మండలాల్లో కొత్తగా కాలువల అనుసంధాన పనులకు మంత్రులు శంకుస్థాపన చేశారు.',
    content: 'ఈ పథకం వల్ల దాదాపు 30 వేల ఎకరాల అదనపు భూమి సాగులోకి రానుందని అధికారులు పేర్కొన్నారు.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: '/khammam_agriculture.png',
    author: 'ఖమ్మం రిపోర్టర్',
    publishedAt: '2026-06-04T14:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 7900,
    tags: ['ఖమ్మం', 'తెలంగాణ', 'వ్యవసాయం'],
    districtSlug: 'khammam'
  },
  {
    id: 'tg-dist-6',
    slug: 'nalgonda-nagarjuna-sagar-water-release',
    title: 'నల్గొండలో నాగార్జున సాగర్ నీటి విడుదల - రైతుల హర్షం',
    description: 'ఎగువ ప్రాంతాల నుంచి భారీ వరదలు వస్తుండటంతో నాగార్జున సాగర్ రిజర్వాయర్ గేట్లను తెరిచి నీటిని విడుదల చేశారు.',
    content: 'ఆయకట్టు పరిధిలోని రైతులకు సాగునీరు అందుతుండటంతో వ్యవసాయ పనులు ఊపందుకున్నాయి.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&h=450&fit=crop',
    author: 'సాగర్ ప్రతినిధి',
    publishedAt: '2026-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 16800,
    tags: ['నల్గొండ', 'తెలంగాణ', 'నాగార్జున సాగర్', 'నీరు'],
    districtSlug: 'nalgonda'
  },
  {
    id: 'tg-dist-7',
    slug: 'mahabubnagar-it-tower-ready',
    title: 'మహబూబ్‌నగర్ జిల్లాలో ఐటీ టవర్ పనులు పూర్తి - త్వరలో ప్రారంభం',
    description: 'మహబూబ్‌నగర్ జిల్లా కేంద్రంలో అధునాతన సౌకర్యాలతో నిర్మించిన ఐటీ టవర్ ప్రారంభానికి సిద్ధమైంది.',
    content: 'స్థానిక యువతకు ఐటీ ఉద్యోగావకాశాలు కల్పించడమే ధ్యేయంగా ఈ టవర్ నిర్మించారు. పలు కంపెనీలు తమ ఆఫీసులను ప్రారంభించనున్నాయి.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=450&fit=crop',
    author: 'మహబూబ్‌నగర్ ప్రతినిధి',
    publishedAt: '2026-06-04T10:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 11000,
    tags: ['మహబూబ్‌నగర్', 'తెలంగాణ', 'ఐటీ టవర్'],
    districtSlug: 'mahabubnagar'
  },
  {
    id: 'tg-dist-8',
    slug: 'adilabad-forests-tourism-development',
    title: 'ఆదిలాబాద్ అడవులలో పర్యాటక రంగ అభివృద్ధికి చర్యలు',
    description: 'ఉమ్మడి ఆదిలాబాద్ జిల్లాలోని జలపాతాలు, అటవీ ప్రాంతాలలో పర్యాటకులను ఆకర్షించేందుకు ప్రత్యేక సదుపాయాలు కల్పిస్తున్నారు.',
    content: 'కుంతాల జలపాతం, సహ్యాద్రి శ్రేణులలో పర్యాటక శాఖ ద్వారా గైడ్లు మరియు వసతి సౌకర్యాలు ఏర్పాటు చేయనున్నారు.',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800&h=450&fit=crop',
    author: 'ఆదిలాబాద్ బ్యూరో',
    publishedAt: '2026-06-04T08:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 9500,
    tags: ['ఆదిలాబాద్', 'తెలంగాణ', 'అడవులు', 'పర్యాటకం'],
    districtSlug: 'adilabad'
  }
];

export const breakingNews: string[] = [
  'ఆంధ్రప్రదేశ్‌లో భారీ వర్షాలు - జిల్లాల్లో అలర్ట్ జారీ',
  'హైదరాబాద్‌లో మెట్రో రైలు విస్తరణకు ప్రభుత్వం ఆమోదం',
  'తెలంగాణ బడ్జెట్ సమావేశాలు రేపటి నుంచి ప్రారంభం',
  'భారత క్రికెట్ జట్టు వన్డే సిరీస్‌లో విజయం - 3-0తో గెలుపు',
  'సెన్సెక్స్ 200 పాయింట్లు పెరిగింది - మార్కెట్లో ర్యాలీ',
  'రాజకీయ నాయకుడు సభలో సంచలన వ్యాఖ్యలు',
  'AI రంగంలో భారత్ అగ్రస్థానానికి చేరుకుంటుందని నిపుణుల అంచనా',
];

export const featuredNews: NewsArticle[] = [
  {
    id: '1',
    slug: 'ap-heavy-rains-alert-2024',
    title: 'ఆంధ్రప్రదేశ్‌లో భారీ వర్షాలు: పలు జిల్లాల్లో రెడ్ అలర్ట్ జారీ చేసిన వాతావరణ శాఖ',
    description: 'రాష్ట్రంలో ముందస్తు రుతుపవనాలు ప్రవేశించిన నేపథ్యంలో తీరప్రాంత జిల్లాలు సహా పలు ప్రాంతాల్లో భారీ వర్షాలు కురుస్తున్నాయి.',
    content: 'ఆంధ్రప్రదేశ్ తీరప్రాంత జిల్లాలలో భారీ వర్షాలు కురుస్తున్న నేపథ్యంలో వాతావరణ శాఖ అలర్ట్ జారీ చేసింది...',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=675&fit=crop',
    author: 'హై టీవీ రిపోర్టర్',
    publishedAt: '2024-06-05T08:30:00Z',
    isBreaking: true,
    isTrending: true,
    isFeatured: true,
    views: 45230,
    tags: ['వర్షాలు', 'ఆంధ్రప్రదేశ్', 'అలర్ట్'],
  },
  {
    id: '2',
    slug: 'telangana-metro-expansion',
    title: 'హైదరాబాద్ మెట్రో విస్తరణకు కేంద్ర ప్రభుత్వం ₹18,000 కోట్ల నిధులకు ఆమోదం',
    description: 'హైదరాబాద్ మెట్రో రైలు నెట్‌వర్క్‌ను మరింత విస్తరించేందుకు కేంద్ర ప్రభుత్వం భారీ నిధులు మంజూరు చేసింది.',
    content: 'కేంద్ర మంత్రివర్గం బుధవారం హైదరాబాద్ మెట్రో విస్తరణ ప్రాజెక్ట్‌కు ₹18,000 కోట్ల నిధులకు ఆమోదం తెలిపింది...',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=675&fit=crop',
    author: 'హై టీవీ డెస్క్',
    publishedAt: '2024-06-05T07:15:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: true,
    views: 32100,
    tags: ['మెట్రో', 'హైదరాబాద్', 'తెలంగాణ'],
  },
  {
    id: '3',
    slug: 'india-cricket-odi-series-win',
    title: 'భారత్ వన్డే సిరీస్ గెలుపు: రోహిత్ నేతృత్వంలో క్లీన్ స్వీప్ - అభిమానులలో సంబురాలు',
    description: 'భారత క్రికెట్ జట్టు మూడు వన్డే మ్యాచ్‌ల సిరీస్‌లో 3-0తో క్లీన్ స్వీప్ సాధించింది.',
    content: 'టీమ్ ఇండియా వన్డే క్రికెట్ సిరీస్‌లో అద్భుతమైన ఆట ప్రదర్శించి...',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=675&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-05T06:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: true,
    views: 67890,
    tags: ['క్రికెట్', 'భారత్', 'వన్డే'],
  },
  {
    id: '4',
    slug: 'sensex-rally-market-high',
    title: 'సెన్సెక్స్ కొత్త రికార్డు స్థాయికి: 200 పాయింట్లు పెరిగి 80,000 అంకె దాటింది',
    description: 'బాంబే స్టాక్ ఎక్స్ఛేంజ్ సూచీ నూతన అత్యధిక స్థాయికి చేరుకుంది. విదేశీ పెట్టుబడులు పెరగడంతో మార్కెట్‌లో జోష్.',
    content: 'దేశీయ స్టాక్ మార్కెట్ సూచీలు బుధవారం భారీగా పెరిగాయి...',
    category: 'వ్యాపారం',
    categorySlug: 'business',
    categoryColor: '#15803d',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=675&fit=crop',
    author: 'ఆర్థిక విభాగం',
    publishedAt: '2024-06-05T05:45:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: true,
    views: 28450,
    tags: ['సెన్సెక్స్', 'మార్కెట్', 'పెట్టుబడులు'],
  },
];

export const politicsNews: NewsArticle[] = [
  {
    id: '10',
    slug: 'ap-cm-budget-announcement',
    title: 'ఆంధ్రప్రదేశ్ ముఖ్యమంత్రి సంచలన ప్రకటన: రైతులకు ₹5,000 కోట్ల ప్యాకేజీ',
    description: 'రాష్ట్ర ప్రభుత్వం రైతు సంక్షేమం కోసం భారీ ఆర్థిక ప్యాకేజీ ప్రకటించింది.',
    content: '',
    category: 'రాజకీయాలు',
    categorySlug: 'politics',
    categoryColor: '#1a6b3a',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=450&fit=crop',
    author: 'రాజకీయ విభాగం',
    publishedAt: '2024-06-05T09:00:00Z',
    isBreaking: true,
    isTrending: false,
    isFeatured: false,
    views: 34500,
    tags: ['రాజకీయాలు', 'ఆంధ్రప్రదేశ్', 'రైతులు'],
  },
  {
    id: '11',
    slug: 'telangana-opposition-press-meet',
    title: 'తెలంగాణలో విపక్ష పార్టీల సంయుక్త సమావేశం - ప్రభుత్వంపై తీవ్ర విమర్శలు',
    description: 'విపక్ష నేతలు ప్రభుత్వ విధానాలను తీవ్రంగా విమర్శిస్తూ పలు ఆరోపణలు చేశారు.',
    content: '',
    category: 'రాజకీయాలు',
    categorySlug: 'politics',
    categoryColor: '#1a6b3a',
    image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=450&fit=crop',
    author: 'రాజకీయ విభాగం',
    publishedAt: '2024-06-05T08:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 21300,
    tags: ['రాజకీయాలు', 'తెలంగాణ', 'విపక్షం'],
  },
  {
    id: '12',
    slug: 'parliament-session-highlights',
    title: 'పార్లమెంట్ సమావేశంలో వేడి చర్చ: విపక్షం వాకౌట్ - సభలో గందరగోళం',
    description: 'కేంద్ర పార్లమెంట్ బడ్జెట్ సమావేశంలో ప్రతిపక్ష సభ్యులు నిరసన తెలిపి వాకౌట్ చేశారు.',
    content: '',
    category: 'జాతీయ',
    categorySlug: 'national',
    categoryColor: '#0369a1',
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&h=450&fit=crop',
    author: 'ఢిల్లీ బ్యూరో',
    publishedAt: '2024-06-05T07:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 18900,
    tags: ['పార్లమెంట్', 'జాతీయ', 'విపక్షం'],
  },
  {
    id: '13',
    slug: 'election-commission-announcement',
    title: 'ఎన్నికల కమిషన్ కీలక నిర్ణయం: ఉప ఎన్నికలకు తేదీలు ప్రకటన',
    description: 'కేంద్ర ఎన్నికల కమిషన్ పలు నియోజకవర్గాలలో జరిగే ఉప ఎన్నికల షెడ్యూలు విడుదల చేసింది.',
    content: '',
    category: 'రాజకీయాలు',
    categorySlug: 'politics',
    categoryColor: '#1a6b3a',
    image: 'https://images.unsplash.com/photo-1494172961521-33799ddd43a5?w=800&h=450&fit=crop',
    author: 'రాజకీయ విభాగం',
    publishedAt: '2024-06-04T14:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 15600,
    tags: ['ఎన్నికలు', 'కమిషన్'],
  },
];

export const entertainmentNews: NewsArticle[] = [
  {
    id: '20',
    slug: 'tollywood-blockbuster-release',
    title: 'టాలీవుడ్ బ్లాక్‌బస్టర్: పెద్ద హీరో కొత్త చిత్రం మొదటి రోజు ₹100 కోట్లు వసూలు',
    description: 'తెలుగు సినీ ప్రేక్షకులు పెద్ద సంఖ్యలో థియేటర్లకు తరలివెళ్ళారు. ట్రేడ్ అనలిస్టులు ఆశ్చర్యం వ్యక్తం.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-05T10:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 89000,
    tags: ['సినిమా', 'టాలీవుడ్', 'బాక్సాఫీస్'],
  },
  {
    id: '21',
    slug: 'actress-award-ceremony',
    title: 'ఫిల్మ్‌ఫేర్ అవార్డ్స్ సందడి: తెలుగు నటీనటులు పలు పురస్కారాలు అందుకున్నారు',
    description: 'ప్రతిష్ఠాత్మక ఫిల్మ్‌ఫేర్ అవార్డ్స్ వేడుకలో తెలుగు చిత్రసీమ తళతళ మెరిసింది.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-04T20:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 54300,
    tags: ['అవార్డులు', 'సినిమా', 'తెలుగు'],
  },
  {
    id: '22',
    slug: 'ott-new-series-release',
    title: 'OTT సంచలనం: నెట్‌ఫ్లిక్స్‌లో తెలుగు వెబ్ సిరీస్ విడుదల - ప్రేక్షకుల మెచ్చుకోలు',
    description: 'తెలుగులో నేరుగా OTT ప్లాట్‌ఫామ్‌పై విడుదలైన వెబ్ సిరీస్ భారీ ఆదరణ పొందుతుంది.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-04T16:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 43200,
    tags: ['OTT', 'వెబ్ సిరీస్', 'నెట్‌ఫ్లిక్స్'],
  },
  {
    id: '23',
    slug: 'hero-new-movie-announcement',
    title: 'సూపర్ స్టార్ కొత్త చిత్రం ప్రకటన: బిగ్ బడ్జెట్ యాక్షన్ థ్రిల్లర్ తయారీ మొదలు',
    description: 'తెలుగు చలనచిత్ర పరిశ్రమలో సంచలనం రేపుతున్న నటుడు కొత్త చిత్రం ప్రారంభోత్సవం.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 62100,
    tags: ['సినిమా', 'టాలీవుడ్', 'యాక్షన్'],
  },
];

export const sportsNews: NewsArticle[] = [
  {
    id: '30',
    slug: 'ipl-final-match-report',
    title: 'IPL ఫైనల్ మ్యాచ్: రోమాంచకర పోరాటంలో హైదరాబాద్ జట్టు ఛాంపియన్',
    description: 'ఇండియన్ ప్రీమియర్ లీగ్ ఫైనల్‌లో హైదరాబాద్ జట్టు అద్భుత విజయం సాధించింది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-05T11:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 98500,
    tags: ['IPL', 'క్రికెట్', 'హైదరాబాద్'],
  },
  {
    id: '31',
    slug: 'badminton-world-championship',
    title: 'బ్యాడ్మింటన్ విజయం: భారత ఆటగాడు వరల్డ్ ఛాంపియన్‌షిప్‌లో స్వర్ణం',
    description: 'తెలుగు తేజం బ్యాడ్మింటన్ కోర్ట్‌పై మెరిసి ప్రపంచ ఛాంపియన్ పట్టం నొంది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-04T18:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 45600,
    tags: ['బ్యాడ్మింటన్', 'చాంపియన్', 'భారత్'],
  },
  {
    id: '32',
    slug: 'pro-kabaddi-results',
    title: 'ప్రో కబడ్డీ: తెలుగు టైటాన్స్ అద్భుత గెలుపు - ప్లేఆఫ్స్‌కు అర్హత',
    description: 'ప్రో కబడ్డీ లీగ్‌లో తెలుగు టైటాన్స్ జట్టు ప్లేఆఫ్స్‌కు అర్హత సాధించింది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-04T15:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 32100,
    tags: ['కబడ్డీ', 'తెలుగు టైటాన్స్'],
  },
  {
    id: '33',
    slug: 'football-premier-league',
    title: 'ఫుట్‌బాల్: ప్రీమియర్ లీగ్ టైటిల్ రేసులో మాంచెస్టర్ సిటీ ముందంజ',
    description: 'ఇంగ్లిష్ ప్రీమియర్ లీగ్‌లో టైటిల్ పోటీలో మాంచెస్టర్ సిటీ ముందు నిలిచింది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: '/football_news_banner.png',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-04T10:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 24300,
    tags: ['ఫుట్‌బాల్', 'ప్రీమియర్ లీగ్'],
  },
];

export const technologyNews: NewsArticle[] = [
  {
    id: '40',
    slug: 'ai-revolution-india',
    title: 'AI విప్లవం: భారత్‌లో కృత్రిమ మేధ స్టార్టప్‌లు ₹50,000 కోట్ల పెట్టుబడులు ఆకర్షించాయి',
    description: 'కృత్రిమ మేధ రంగంలో భారతీయ స్టార్టప్‌లు అంతర్జాతీయ పెట్టుబడిదారులను ఆకర్షిస్తున్నాయి.',
    content: '',
    category: 'టెక్నాలజీ',
    categorySlug: 'technology',
    categoryColor: '#4f46e5',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=450&fit=crop',
    author: 'టెక్ విభాగం',
    publishedAt: '2024-06-05T09:30:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 38900,
    tags: ['AI', 'స్టార్టప్', 'భారత్'],
  },
  {
    id: '41',
    slug: 'smartphone-new-launch',
    title: 'స్మార్ట్‌ఫోన్ విప్లవం: సాంసంగ్ కొత్త ఫోల్డబుల్ ఫోన్ భారత మార్కెట్లో లాంచ్',
    description: 'సాంసంగ్ తాజా ఫోల్డబుల్ స్మార్ట్‌ఫోన్ భారత్‌లో అందుబాటులోకి వచ్చింది.',
    content: '',
    category: 'టెక్నాలజీ',
    categorySlug: 'technology',
    categoryColor: '#4f46e5',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=450&fit=crop',
    author: 'టెక్ విభాగం',
    publishedAt: '2024-06-04T14:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 29700,
    tags: ['స్మార్ట్‌ఫోన్', 'సాంసంగ్', 'మొబైల్'],
  },
];

export const businessNews: NewsArticle[] = [
  {
    id: '50',
    slug: 'rbi-repo-rate-decision',
    title: 'RBI కీలక నిర్ణయం: రెపో రేట్ మార్పు లేదు - ద్రవ్యోల్బణం నియంత్రణపై దృష్టి',
    description: 'రిజర్వ్ బ్యాంక్ ఆఫ్ ఇండియా వడ్డీ రేట్లను యథాతథంగా కొనసాగించాలని నిర్ణయించింది.',
    content: '',
    category: 'వ్యాపారం',
    categorySlug: 'business',
    categoryColor: '#15803d',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop',
    author: 'ఆర్థిక విభాగం',
    publishedAt: '2024-06-05T10:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 22400,
    tags: ['RBI', 'వడ్డీ రేట్లు', 'ఆర్థికం'],
  },
  {
    id: '51',
    slug: 'real-estate-boom-hyderabad',
    title: 'హైదరాబాద్‌లో రియల్ ఎస్టేట్ బూమ్: అపార్ట్‌మెంట్ ధరలు 30% పెరుగుదల',
    description: 'IT హబ్ హైదరాబాద్‌లో రియల్ ఎస్టేట్ మార్కెట్ జోరందుకుంది. ఫ్లాట్ ధరలు భారీగా పెరుగుతున్నాయి.',
    content: '',
    category: 'వ్యాపారం',
    categorySlug: 'business',
    categoryColor: '#15803d',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop',
    author: 'ఆర్థిక విభాగం',
    publishedAt: '2024-06-04T16:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 31200,
    tags: ['రియల్ ఎస్టేట్', 'హైదరాబాద్'],
  },
];

export const healthNews: NewsArticle[] = [
  {
    id: '60',
    slug: 'monsoon-diseases-prevention',
    title: 'వర్షాకాలంలో జాగ్రత్తలు: డెంగీ, మలేరియా నివారణకు ఆరోగ్య శాఖ సూచనలు',
    description: 'రుతుపవనాల సీజన్‌లో సాధారణంగా వ్యాప్తి చెందే వ్యాధుల నివారణకు ఆరోగ్య శాఖ గైడ్‌లైన్స్ జారీ.',
    content: '',
    category: 'ఆరోగ్యం',
    categorySlug: 'health',
    categoryColor: '#0891b2',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=450&fit=crop',
    author: 'ఆరోగ్య విభాగం',
    publishedAt: '2024-06-05T08:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 18700,
    tags: ['ఆరోగ్యం', 'వర్షాకాలం', 'వ్యాధులు'],
  },
];

export const viralNews: NewsArticle[] = [
  {
    id: '70',
    slug: 'viral-video-dog-saves-child',
    title: 'వైరల్ వీడియో: నీటిలో మునిగిపోతున్న పిల్లవాడిని కుక్క రక్షించిన వీడియో నెట్‌లో సంచలనం',
    description: 'ఒక చిన్న పిల్లవాడిని కాపాడిన కుక్క వీడియో సోషల్ మీడియాలో వైరల్ అయింది.',
    content: '',
    category: 'వైరల్',
    categorySlug: 'viral',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=450&fit=crop',
    author: 'డిజిటల్ విభాగం',
    publishedAt: '2024-06-05T07:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 125000,
    tags: ['వైరల్', 'వీడియో', 'సోషల్ మీడియా'],
  },
];

export const videoNews: NewsArticle[] = [
  {
    id: '80',
    slug: 'video-ap-floods-coverage',
    title: 'ఆంధ్రప్రదేశ్ వరదలు: భారీ నీటి ప్రవాహం వీడియో - ప్రభావిత ప్రాంతాల దృశ్యాలు',
    description: 'AP వరదలపై ప్రత్యేక వీడియో కవరేజ్.',
    content: '',
    category: 'వీడియోలు',
    categorySlug: 'videos',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop',
    author: 'వీడియో విభాగం',
    publishedAt: '2024-06-05T09:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 56000,
    tags: ['వీడియో', 'వరదలు'],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: '81',
    slug: 'video-cricket-highlights',
    title: 'క్రికెట్ హైలైట్స్: భారత్ vs ఆస్ట్రేలియా మ్యాచ్ అత్యుత్తమ క్షణాలు',
    description: 'మ్యాచ్ హైలైట్స్ వీడియో కవరేజ్.',
    content: '',
    category: 'వీడియోలు',
    categorySlug: 'videos',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&h=450&fit=crop',
    author: 'వీడియో విభాగం',
    publishedAt: '2024-06-04T20:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 87000,
    tags: ['క్రికెట్', 'వీడియో'],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: '82',
    slug: 'video-budget-analysis',
    title: 'బడ్జెట్ విశ్లేషణ: నిపుణులు చెప్పే అంశాలు - నేరుగా మీకు',
    description: 'బడ్జెట్ ప్రతిపాదనలపై నిపుణుల విశ్లేషణ.',
    content: '',
    category: 'వీడియోలు',
    categorySlug: 'videos',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop',
    author: 'వీడియో విభాగం',
    publishedAt: '2024-06-04T16:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 43200,
    tags: ['బడ్జెట్', 'వీడియో', 'విశ్లేషణ'],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
];

export const rasipalaluNews: NewsArticle[] = [
  {
    id: '90',
    slug: 'daily-horoscope-june-5-2026',
    title: 'నేటి రాశిఫలాలు: జూన్ 5, 2026 నాటి ద్వాదశ రాశిఫలాలు.. ఈ రాశి వారికి ఆకస్మిక ధనలాభం!',
    description: 'నేటి రోజు మీ రాశి ఫలాలు ఎలా ఉన్నాయి? ఏ రాశి వారికి అనుకూలంగా ఉంది? ఏ రాశి వారు అప్రమత్తంగా ఉండాలో ఇక్కడ తెలుసుకోండి.',
    content: 'నేటి రోజు మీ రాశి ఫలాలు ఎలా ఉన్నాయి? మేష రాశి నుండి మీన రాశి వరకు గల ద్వాదశ రాశుల ఫలితాలు ఇక్కడ తెలుసుకోండి. మేష రాశి: అనుకూల సమయం, ఉద్యోగంలో పురోగతి ఉంటుంది. వృషభ రాశి: ప్రయాణాల్లో జాగ్రత్త అవసరం. మిథున రాశి: ఆకస్మిక ధనలాభం కలిగే అవకాశం ఉంది. కర్కాటక రాశి: కుటుంబ సభ్యులతో ఆనందంగా గడుపుతారు. సింహ రాశి: వ్యాపారంలో లాభాలు వస్తాయి. కన్యా రాశి: ఆరోగ్యంపై శ్రద్ధ వహించండి. తులా రాశి: నూతన పనులు ప్రారంభిస్తారు. వృశ్చిక రాశి: ఖర్చులు పెరుగుతాయి. ధనుస్సు రాశి: పనులన్నీ సజావుగా సాగుతాయి. మకర రాశి: గౌరవ ప్రతిష్టలు పెరుగుతాయి. కుంభ రాశి: శుభవార్తలు వింటారు. మీన రాశి: మిశ్రమ ఫలితాలు ఉంటాయి.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=450&fit=crop',
    author: 'హై టీవీ భక్తి విభాగం',
    publishedAt: '2026-06-05T06:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 15400,
    tags: ['రాశిఫలాలు', 'నేటి రాశిఫలాలు', 'జ్యోతిష్యం', 'భక్తి'],
  },
  {
    id: '91',
    slug: 'weekly-horoscope-june-5-to-11',
    title: 'వారఫలాలు: జూన్ 5 నుంచి జూన్ 11 వరకు.. ఈ రాశుల వారికి ఉద్యోగంలో ప్రమోషన్!',
    description: 'ఈ వారంలో ద్వాదశ రాశుల వారి జాతకం ఎలా ఉండబోతోంది? ఎవరికి కెరీర్ మెరుగ్గా ఉంటుంది? ఆరోగ్య విషయాల్లో ఎలాంటి జాగ్రత్తలు తీసుకోవాలి?',
    content: 'ఈ వారం ద్వాదశ రాశుల వారి భవిష్యత్తు ఎలా ఉండబోతోందంటే... మేష రాశి వారికి ఉద్యోగంలో అనుకూలమైన మార్పులు ఉంటాయి, ప్రమోషన్ లభించే అవకాశం ఉంది. వృషభ రాశి వారు ఆర్థిక విషయాల్లో జాగ్రత్తగా ఉండాలి. మిథున రాశి విద్యార్థులు విజయం సాధిస్తారు. కర్కాటక రాశి వారికి గృహ నిర్మాణ పనులు వేగవంతం అవుతాయి. సింహ రాశి వారికి వ్యాపార విస్తరణకు అనుకూలం. కన్యా రాశి వారు వివాదాలకు దూరంగా ఉండాలి. తులా రాశి ఉద్యోగస్తులకు ప్రశంసలు దక్కుతాయి. వృశ్చిక రాశి వారికి ప్రయాణాల వల్ల ప్రయోజనం. ధనుస్సు రాశి వారు ఆరోగ్యాన్ని నిర్లక్ష్యం చేయవద్దు. మకర రాశి వారికి ఆశించిన అవకాశాలు వస్తాయి. కుంభ రాశి వారు శుభకార్యాల్లో పాల్గొంటారు. మీన రాశి వారికి పనులు విజయవంతంగా పూర్తవుతాయి.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1532960401447-7dd05bef20b0?w=800&h=450&fit=crop',
    author: 'ఆచార్య కృష్ణప్రసాద్',
    publishedAt: '2026-06-05T05:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 22800,
    tags: ['వారఫలాలు', 'రాశిఫలాలు', 'జాతకం', 'గ్రహాలు'],
  },
  {
    id: '92',
    slug: 'yearly-horoscope-forecast-2026',
    title: 'సంవత్సర రాశిఫలాలు 2026: మీ రాశికి ఈ సంవత్సరం ఎలాంటి ఫలితాలు రాబోతున్నాయి?',
    description: 'నూతన సంవత్సరంలో ద్వాదశ రాశుల వారి గ్రహాల సంచారం ఆధారంగా కెరీర్, పెళ్లి, కుటుంబం మరియు ఆర్థిక స్థితిగతుల విశ్లేషణ.',
    content: '2026 సంవత్సరంలో గురు, శని, రాహు-కేతువుల సంచారం వల్ల ద్వాదశ రాశుల వారికి విభిన్న ఫలితాలు రాబోతున్నాయి. మేష, సింహ, ధనుస్సు రాశుల వారికి ఈ సంవత్సరం అద్భుతమైన కెరీర్ ఎదుగుదల మరియు ఆర్థిక స్థిరత్వం ఉంటుంది. వృషభ, కన్య, మకర రాశుల వారికి మధ్యస్థ ఫలితాలు ఉంటాయి. మిథున, తుల, కుంభ రాశుల వారు ఆరోగ్య విషయాల్లో అప్రమత్తంగా ఉండాలి. కర్కాటక, వృశ్చిక, మీన రాశుల వారికి సామాజికంగా గౌరవ ప్రతిష్టలు లభిస్తాయి.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=800&h=450&fit=crop',
    author: 'సిద్ధాంతి సుబ్రహ్మణ్య శర్మ',
    publishedAt: '2026-06-04T18:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 41200,
    tags: ['సంవత్సర ఫలాలు', 'రాశిఫలాలు', '2026 జాతకం'],
  },
  {
    id: '93',
    slug: 'saturn-transit-effects-and-remedies-2026',
    title: 'శని గోచారం 2026: శని దేవుడి సంచారం వల్ల ఈ మూడు రాశుల వారికి విపరీతమైన రాజయోగం!',
    description: 'కుంభ రాశిలో శని సంచారం వల్ల ఏ రాశుల వారికి సానుకూల ఫలితాలు వస్తాయి? ఎలాంటి పరిహారాలు చేయాలో పూర్తి వివరాలు.',
    content: 'శని దేవుడు స్వక్షేత్రమైన కుంభ రాశిలో సంచరించడం వల్ల కొన్ని రాశుల వారికి శశ మహాపురుష యోగం పడుతోంది. దీనివల్ల మేషం, మిథునం, మరియు తులా రాశుల వారికి అపారమైన కీర్తి, సంపద దక్కుతాయి. శని ప్రభావం వల్ల ఏదైనా ఆటంకాలు ఎదురైతే శనివారం నాడు నువ్వుల నూనెతో దీపారాధన చేయడం, హనుమాన్ చాలీసా పఠించడం ద్వారా ఉపశమనం లభిస్తుంది.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=800&h=450&fit=crop',
    author: 'హై టీవీ భక్తి విభాగం',
    publishedAt: '2026-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 35000,
    tags: ['శని దేవుడు', 'శని గోచారం', 'జ్యోతిష్యం'],
  },
];


export const womenNews: NewsArticle[] = [
  {
    id: 'w-1',
    slug: 'women-empowerment-loans',
    title: 'మహిళా సాధికారత: స్వయం సహాయక సంఘాలకు రూ. 3,000 కోట్ల వడ్డీ లేని రుణాలు',
    description: 'మహిళల ఆర్థిక స్వావలంబన కోసం ప్రభుత్వం విప్లవాత్మక నిర్ణయం తీసుకుంది. స్వయం సహాయక సంఘాలకు వడ్డీ లేని రుణాలను ప్రకటించింది.',
    content: 'రాష్ట్రవ్యాప్తంగా ఉన్న కోట్లాది మంది మహిళల ఉపాధి అవకాశాలను పెంచేందుకు గాను, ప్రభుత్వం ఈ భారీ ప్యాకేజీని అమలు చేస్తోంది. దీని ద్వారా మహిళలు సొంతంగా వ్యాపారాలను ప్రారంభించుకునే అవకాశం లభిస్తుంది.',
    category: 'మహిళలు',
    categorySlug: 'women',
    categoryColor: '#ec4899',
    image: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&h=450&fit=crop',
    author: 'హై టీవీ బ్యూరో',
    publishedAt: '2026-06-05T09:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 28900,
    tags: ['మహిళలు', 'రుణాలు', 'ఆర్థికం'],
  },
  {
    id: 'w-2',
    slug: 'free-gas-cylinders-scheme',
    title: 'గృహిణులకు గుడ్ న్యూస్: ఉచిత గ్యాస్ సిలిండర్ల పంపిణీకి శ్రీకారం చుట్టిన ప్రభుత్వం',
    description: 'రాష్ట్రంలోని అర్హులైన ప్రతి గృహిణికి సంవత్సరానికి మూడు ఉచిత గ్యాస్ సిలిండర్లు ఇచ్చే పథకాన్ని ఈ రోజు ప్రారంభించారు.',
    content: 'ఈ పథకం వల్ల గ్రామీణ మరియు పట్టణ ప్రాంతాలలోని పేద మహిళలకు ఎంతో ప్రయోజనం చేకూరుతుంది. మొదటి విడత కింద నేడు వేలాది మందికి సిలిండర్లను మంత్రులు పంపిణీ చేశారు.',
    category: 'మహిళలు',
    categorySlug: 'women',
    categoryColor: '#ec4899',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=450&fit=crop',
    author: 'మహిళా ప్రతినిధి',
    publishedAt: '2026-06-04T15:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 31200,
    tags: ['మహిళలు', 'గ్యాస్ సిలిండర్', 'పథకాలు'],
  }
];

export const lifestyleNews: NewsArticle[] = [
  {
    id: 'l-1',
    slug: 'modern-lifestyle-stress-management',
    title: 'ఆధునిక జీవనశైలి: ఒత్తిడిని జయించేందుకు నిపుణులు చెబుతున్న 5 సులువైన మార్గాలు',
    description: 'ప్రస్తుత బిజీ లైఫ్‌లో ప్రతి ఒక్కరూ ఎదుర్కొంటున్న ప్రధాన సమస్య ఒత్తిడి. దీనిని అధిగమించడానికి జీవనశైలిలో చిన్న మార్పులు చేయాలి.',
    content: 'ధ్యానం, సరైన నిద్ర, డిజిటల్ డిటాక్స్, మరియు క్రమం తప్పకుండా వ్యాయామం చేయడం ద్వారా మానసిక ప్రశాంతత లభిస్తుందని మానసిక నిపుణులు సూచిస్తున్నారు.',
    category: 'లైఫ్ స్టైల్',
    categorySlug: 'lifestyle',
    categoryColor: '#9333ea',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=450&fit=crop',
    author: 'లైఫ్ స్టైల్ డెస్క్',
    publishedAt: '2026-06-05T08:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 45000,
    tags: ['ఆరోగ్యం', 'జీవనశైలి', 'యోగా'],
  },
  {
    id: 'l-2',
    slug: 'home-decor-tips-low-budget',
    title: 'ఇంటి అలంకరణ: తక్కువ బడ్జెట్‌లో మీ ఇల్లును అందంగా మార్చుకోవడానికి చిట్కాలు',
    description: 'ఎక్కువ ఖర్చు లేకుండానే మీ ఇంటి లుక్‌ను మార్చేసే అద్భుతమైన గృహాలంకరణ ఐడియాలు మరియు చిట్కాలు ఇక్కడ తెలుసుకోండి.',
    content: 'ఇండోర్ ప్లాంట్లు పెట్టడం, రంగుల కర్టెన్ల వాడకం, మరియు సృజనాత్మక లైటింగ్ ద్వారా మీ పడకగదిని లేదా హాల్‌ను సరికొత్తగా తీర్చిదిద్దవచ్చు.',
    category: 'లైఫ్ స్టైల్',
    categorySlug: 'lifestyle',
    categoryColor: '#9333ea',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=450&fit=crop',
    author: 'ఇంటీరియర్ డిజైనర్ విభాగం',
    publishedAt: '2026-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 23100,
    tags: ['ఇంటి అలంకరణ', 'చిట్కాలు', 'జీవనశైలి'],
  }
];

export const webstoriesNews: NewsArticle[] = [
  {
    id: 'ws-1',
    slug: 'webstories-healthy-skin-morning-drinks',
    title: 'వెబ్ స్టోరీస్: ఆరోగ్యకరమైన చర్మం కోసం ఉదయాన్నే తీసుకోవాల్సిన హెల్తీ డ్రింక్స్ ఇవే!',
    description: 'మెరిసే మరియు కాంతివంతమైన చర్మం కోసం ప్రతిరోజూ ఉదయాన్నే ఈ రసం లేదా పానీయాలు తీసుకోవడం వల్ల అద్భుత ఫలితాలు ఉంటాయి.',
    content: 'తేనె-నిమ్మకాయ నీరు, గ్రీన్ టీ, లేదా కలబంద రసం వంటివి రోజూ తాగడం వల్ల మీ చర్మ సౌందర్యం మెరుగుపడుతుంది మరియు ముడతలు రాకుండా కాపాడుతుంది.',
    category: 'వెబ్ స్టోరీస్',
    categorySlug: 'webstories',
    categoryColor: '#ec4899',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=450&fit=crop',
    author: 'డిజిటల్ విలేఖరి',
    publishedAt: '2026-06-05T07:15:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 78900,
    tags: ['వెబ్ స్టోరీస్', 'చర్మ సంరక్షణ', 'సౌందర్యం'],
  },
  {
    id: 'ws-2',
    slug: 'webstories-weight-loss-superfoods',
    title: 'వెబ్ స్టోరీస్: బరువు తగ్గాలనుకుంటున్నారా? ఈ సూపర్ ఫుడ్స్ మీ డైట్‌లో చేర్చుకోండి',
    description: 'శరీరంలో అదనపు కొవ్వును కరిగించి చురుగ్గా ఉంచేందుకు సహాయపడే కొన్ని పోషక విలువలు ఉన్న ఆహారాల జాబితా.',
    content: 'ఓట్స్, గుడ్లు, రాగులు, మరియు నట్స్ వంటి ఫైబర్ అధికంగా ఉండే ఆహారాలు రోజూ తీసుకోవడం వల్ల బరువు సులభంగా తగ్గుతారు.',
    category: 'వెబ్ స్టోరీస్',
    categorySlug: 'webstories',
    categoryColor: '#ec4899',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=450&fit=crop',
    author: 'ఆరోగ్య డెస్క్',
    publishedAt: '2026-06-04T18:45:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 65400,
    tags: ['వెబ్ స్టోరీస్', 'బరువు తగ్గుట', 'డైట్'],
  }
];

export const antharmadanamNews: NewsArticle[] = [
  {
    id: 'am-1',
    slug: 'antharmadanam-success-mindset-shift',
    title: 'అంతర్మథనం: జీవితంలో విజయం సాధించాలంటే మన ఆలోచనల్లో ఎలాంటి మార్పులు రావాలి?',
    description: 'ఓటమిని అంగీకరిస్తూనే, వాటి నుంచి నేర్చుకుని ముందుకు సాగడమే నిజమైన విజయం. మన అంతరంగంలో జరిగే సంఘర్షణకు సమాధానం ఇక్కడే ఉంది.',
    content: 'జీవిత ప్రయాణంలో ఎదురయ్యే సవాళ్లను అధిగమించడానికి అనుకూల దృక్పథం అవసరం. ఇతరులతో పోల్చుకోకుండా మీ వ్యక్తిత్వాన్ని మెరుగుపరుచుకోవడం పై దృష్టి పెట్టాలి.',
    category: 'అంతర్మథనం',
    categorySlug: 'antharmadanam',
    categoryColor: '#8b5cf6',
    image: 'https://images.unsplash.com/photo-1494172961521-33799ddd43a5?w=800&h=450&fit=crop',
    author: 'తత్వ విశ్లేషణ విభాగం',
    publishedAt: '2026-06-05T08:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 19800,
    tags: ['అంతర్మథనం', 'జీవితం', 'ఆలోచనలు'],
  },
  {
    id: 'am-2',
    slug: 'build-self-confidence-inner-peace',
    title: 'ఆత్మవిశ్వాసం పెంపొందించుకోవడం ఎలా? అంతరంగ శోధన ద్వారానే ప్రశాంతత సాధ్యం',
    description: 'ఆందోళనను దూరం చేసి, మనశ్శాంతిని పొందడానికి రోజువారీ అలవాట్లలో మనం అవలంబించాల్సిన విలువలపై ప్రత్యేక విశ్లేషణ.',
    content: 'బాహ్య ప్రపంచం ఎంతగా ప్రలోభ పెడుతున్నా, అంతర్గతంగా ప్రశాంతంగా ఉండడం ఒక కళ. క్రమం తప్పకుండా స్వీయ విశ్లేషణ చేసుకోవడం వల్ల మానసిక స్థిరత్వం లభిస్తుంది.',
    category: 'అంతర్మథనం',
    categorySlug: 'antharmadanam',
    categoryColor: '#8b5cf6',
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=450&fit=crop',
    author: 'స్ఫూర్తిదాయక బృందం',
    publishedAt: '2026-06-04T10:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 22000,
    tags: ['ఆత్మవిశ్వాసం', 'ప్రశాంతత', 'అంతర్మథనం'],
  }
];

export const adyathmikamNews: NewsArticle[] = [
  {
    id: 'ad-1',
    slug: 'tirumala-srivari-temple-history-secrets',
    title: 'ఆధ్యాత్మికం: తిరుమల శ్రీవారి ఆలయ విశిష్టత మరియు చరిత్ర.. తప్పక తెలుసుకోవాల్సిన రహస్యాలు!',
    description: 'కలియుగ వైకుంఠమైన తిరుమలలో వెలసిన వెంకటేశ్వర స్వామి ఆలయానికి సంబంధించిన పురాణ గాథలు మరియు ఆచార విశేషాలు.',
    content: 'శ్రీవారి ఆలయంలో నిత్యం జరిగే సేవలు, బ్రహ్మోత్సవాల ప్రాముఖ్యత మరియు భక్తుల విశ్వాసాలపై ప్రత్యేక కథనం.',
    category: 'ఆధ్యాత్మికం',
    categorySlug: 'adyathmikam',
    categoryColor: '#f59e0b',
    image: 'https://images.unsplash.com/photo-1600100397608-f010e57bbf1f?w=800&h=450&fit=crop',
    author: 'భక్తి విభాగం',
    publishedAt: '2026-06-05T05:30:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 54100,
    tags: ['భక్తి', 'ఆధ్యాత్మికం', 'తిరుమల'],
  },
  {
    id: 'ad-2',
    slug: 'pooja-room-lamp-directions-lakshmi-devi',
    title: 'పూజ గదిలో ఏ దిశలో దీపారాధన చేస్తే లక్ష్మీదేవి కటాక్షం లభిస్తుంది?',
    description: 'పూజ గదిలో దీపం పెట్టేటప్పుడు ఎలాంటి నియమాలు పాటించాలి? ఏ దిశ వైపు దీపం ఉంచితే ఇంట్లో సిరిసంపదలు కలుగుతాయో శాస్త్రాల ప్రకారం ఇక్కడ తెలుసుకోండి.',
    content: 'తూర్పు దిశగా దీపం వెలిగిస్తే ఆరోగ్యం, పడమర దిశగా వెలిగిస్తే గ్రహదోష నివారణ, మరియు ఉత్తర దిశగా వెలిగిస్తే అష్టైశ్వర్యాలు కలుగుతాయని ఆధ్యాత్మిక పండితులు చెబుతున్నారు.',
    category: 'ఆధ్యాత్మికం',
    categorySlug: 'adyathmikam',
    categoryColor: '#f59e0b',
    image: 'https://images.unsplash.com/photo-1542397284385-60101764553c?w=800&h=450&fit=crop',
    author: 'ఆచార్య కృష్ణ శాస్త్రి',
    publishedAt: '2026-06-04T06:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 38900,
    tags: ['పూజ', 'దీపారాధన', 'శాస్త్రాలు'],
  }
];

export const sampadakiyamNews: NewsArticle[] = [
  {
    id: 'sd-1',
    slug: 'editorial-new-industrial-policies-progress',
    title: 'సంపాదకీయం: నూతన పారిశ్రామిక విధానాలు - అభివృద్ధి పథంలో పురోగతి!',
    description: 'రాష్ట్రంలో పరిశ్రమల స్థాపనకు నూతన సంస్కరణలు తోడ్పడుతున్నాయి. పారదర్శకమైన సింగిల్ విండో విధానంతో పెట్టుబడులు వెల్లువెత్తుతున్నాయి.',
    content: 'యువతకు ఉపాధి కల్పించడంతో పాటు స్థానిక ఆర్థిక వ్యవస్థను పటిష్టం చేయడంలో కొత్త పారిశ్రామిక విధానాలు ఎంతవరకు సఫలీకృతం అవుతాయో పూర్తి విశ్లేషణ.',
    category: 'సంపాదకీయం',
    categorySlug: 'sampadakiyam',
    categoryColor: '#be123c',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=450&fit=crop',
    author: 'ఎడిటోరియల్ డెస్క్',
    publishedAt: '2026-06-05T04:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 15600,
    tags: ['సంపాదకీయం', 'పరిశ్రమలు', 'ఆర్థికం'],
  },
  {
    id: 'sd-2',
    slug: 'editorial-educational-system-reforms',
    title: 'సంపాదకీయం: విద్యా వ్యవస్థలో సంస్కరణలు - నాణ్యమైన విద్యే లక్ష్యంగా ముందడుగు',
    description: 'ప్రాథమిక స్థాయి నుంచి ఉన్నత విద్యా విధానాల వరకు సాంకేతికతను జోడించి బోధన అందించడం ద్వారా నేటి తరాన్ని గ్లోబల్ సిటిజన్లుగా తీర్చిదిద్దవచ్చు.',
    content: 'ప్రభుత్వ పాఠశాలలలో మౌలిక వసతుల కల్పనతో పాటు ఉపాధ్యాయులకు నూతన శిక్షణ కార్యక్రమాలను అందించడం ద్వారా విద్యా నాణ్యతను పెంచవచ్చు.',
    category: 'సంపాదకీయం',
    categorySlug: 'sampadakiyam',
    categoryColor: '#be123c',
    image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=450&fit=crop',
    author: 'ప్రధాన సంపాదకుడు',
    publishedAt: '2026-06-04T05:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 18400,
    tags: ['సంపాదకీయం', 'విద్యా విధానం', 'సంస్కరణలు'],
  }
];

export const galleryImages = [
  { id: 1, src: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=600&h=400&fit=crop', alt: 'రాజకీయ సభ' },
  { id: 2, src: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&h=800&fit=crop', alt: 'క్రికెట్ మ్యాచ్' },
  { id: 3, src: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop', alt: 'వరదలు' },
  { id: 4, src: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&h=600&fit=crop', alt: 'హైదరాబాద్ నగరం' },
  { id: 5, src: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&h=400&fit=crop', alt: 'సినిమా వేడుక' },
  { id: 6, src: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=800&fit=crop', alt: 'స్టాక్ మార్కెట్' },
];


export interface ReporterProfile {
  name: string;
  slug: string;
  role: string;
  bio: string;
  image: string;
}

export const reporterProfiles: Record<string, ReporterProfile> = {
  'suresh': {
    name: 'హై టీవీ రిపోర్టర్ సురేష్',
    slug: 'suresh',
    role: 'జాతీయ రాజకీయాల విశ్లేషకులు & ఢిల్లీ బ్యూరో ఇన్-చార్జ్',
    bio: 'సురేష్ గారు జాతీయ రాజకీయాలు, పార్లమెంట్ వ్యవహారాలు మరియు కేంద్ర ప్రభుత్వ విధానాలపై గత 10 సంవత్సరాలుగా నిరంతరం విశ్లేషణాత్మక కథనాలు అందిస్తున్నారు.',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop'
  },
  'ramesh': {
    name: 'హై టీవీ రిపోర్టర్ రమేష్',
    slug: 'ramesh',
    role: 'ముఖ్య రాజకీయ ప్రతినిధి',
    bio: 'రమేష్ గారు తెలుగు రాష్ట్రాల రాజకీయాలు, ఎన్నికల విశ్లేషణలు మరియు ప్రజా సమస్యలపై ప్రత్యేక కథనాలకు పేరుగాంచారు.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop'
  },
  'swapna': {
    name: 'హై టీవీ రిపోర్టర్ స్వప్న',
    slug: 'swapna',
    role: 'సినిమా & ఎంటర్టైన్మెంట్ రిపోర్టర్',
    bio: 'స్వప్న గారు టాలీవుడ్ చిత్ర పరిశ్రమ విశేషాలు, సినీ ప్రముఖుల ఇంటర్వ్యూలు మరియు చిత్ర సమీక్షలను వేగంగా అందిస్తారు.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop'
  },
  'kiran': {
    name: 'హై టీవీ రిపోర్టర్ కిరణ్',
    slug: 'kiran',
    role: 'క్రీడా విశ్లేషకులు',
    bio: 'కిరణ్ గారు క్రికెట్, బ్యాడ్మింటన్ మరియు ఒలింపిక్ క్రీడల వార్తలను ఎప్పటికప్పుడు పాఠకులకు విశ్లేషణాత్మకంగా చేరవేస్తారు.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop'
  },
  'dr-sarada': {
    name: 'హై టీవీ ప్రతినిధి డా. శారద',
    slug: 'dr-sarada',
    role: 'ఆరోగ్య & జీవనశైలి నిపుణురాలు',
    bio: 'డా. శారద గారు ప్రజా ఆరోగ్యం, వైద్య సలహాలు, ఆహార నియమాలు మరియు యోగా విశిష్టతలపై ఉపయోగకరమైన కథనాలు రాస్తుంటారు.',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop'
  },
  'krishnaprasad': {
    name: 'ఆచార్య కృష్ణప్రసాద్',
    slug: 'krishnaprasad',
    role: 'ఆధ్యాత్మిక సిద్దాంతి',
    bio: 'కృష్ణప్రసాద్ గారు మన సంస్కృతి, పూజా విధానాలు, వ్రతాలు మరియు హిందూ పండుగల ప్రాముఖ్యతను శాస్త్రీయంగా వివరిస్తారు.',
    image: 'https://images.unsplash.com/photo-1607990283143-e81e7a2c93ab?w=400&h=400&fit=crop'
  },
  'subrahmanyam': {
    name: 'సిద్ధాంతి సుబ్రహ్మణ్య శర్మ',
    slug: 'subrahmanyam',
    role: 'ప్రముఖ జ్యోతిష్య నిపుణులు',
    bio: 'సుబ్రహ్మణ్య శర్మ గారు జాతక విశ్లేషణ, గ్రహాల గోచారం మరియు రాశిఫలాలపై ఖచ్చితమైన విశ్లేషణలు అందిస్తూ ప్రజల మన్ననలు పొందారు.',
    image: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=400&h=400&fit=crop'
  },
  'default': {
    name: 'హై టీవీ రిపోర్టర్ సురేష్',
    slug: 'suresh',
    role: 'స్టాఫ్ రిపోర్టర్',
    bio: 'హై టీవీ వార్తా విభాగం నిరంతరం నిజాయితీతో కూడిన వార్తలను సేకరించి ప్రజల ముందుకు తెస్తుంది.',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop'
  }
};

export const authorToReporterSlugMap: Record<string, string> = {
  'ఢిల్లీ బ్యూరో': 'suresh',
  'హై టీవీ బ్యూరో': 'suresh',
  'హై టీవీ రిపోర్టర్': 'suresh',
  'రాజమండ్రి ప్రతినిధి': 'suresh',
  'నెల్లూరు రిపోర్టర్': 'suresh',
  'ఖమ్మం రిపోర్టర్': 'suresh',
  'విలేఖరి': 'suresh',
  'డిజిటల్ విలేఖరి': 'suresh',

  'రాజకీయ విభాగం': 'ramesh',
  'హై టీవీ డెస్క్': 'ramesh',
  'కర్నూలు డెస్క్': 'ramesh',
  'కడప బ్యూరో': 'ramesh',
  'గుంటూరు ప్రతినిధి': 'ramesh',
  'తిరుమల ప్రతినిధి': 'ramesh',
  'హైదరాబాద్ రిపోర్టర్': 'ramesh',
  'వరంగల్ ప్రతినిధి': 'ramesh',
  'నిజామాబాద్ బ్యూరో': 'ramesh',
  'కరీంనగర్ డెస్క్': 'ramesh',
  'సాగర్ ప్రతినిధి': 'ramesh',
  'మహబూబ్‌నగర్ ప్రతినిధి': 'ramesh',
  'ఆదిలాబాద్ బ్యూరో': 'ramesh',
  'ఎడిటోరియల్ డెస్క్': 'ramesh',
  'ప్రధాన సంపాదకుడు': 'ramesh',

  'సినిమా విభాగం': 'swapna',
  'డిజిటల్ విభాగం': 'swapna',
  'మహిళా ప్రతినిధి': 'swapna',
  'తత్వ విశ్లేషణ విభాగం': 'swapna',
  'స్ఫూర్తిదాయక బృందం': 'swapna',

  'క్రీడా విభాగం': 'kiran',
  'వైరల్': 'kiran',
  'వైరల్ విభాగం': 'kiran',
  'వీడియో విభాగం': 'kiran',

  'ఆరోగ్య విభాగం': 'dr-sarada',
  'ఆరోగ్య డెస్క్': 'dr-sarada',
  'లైఫ్ స్టైల్ డెస్క్': 'dr-sarada',
  'ఇంటీరియర్ డిజైనర్ విభాగం': 'dr-sarada',

  'ఆచార్య కృష్ణప్రసాద్': 'krishnaprasad',
  'భక్తి విభాగం': 'krishnaprasad',
  'హై టీవీ భక్తి విభాగం': 'krishnaprasad',
  'ఆచార్య కృష్ణ శాస్త్రి': 'krishnaprasad',

  'సిద్ధాంతి సుబ్రహ్మణ్య శర్మ': 'subrahmanyam',
};

export function getReporterByAuthor(authorName: string): ReporterProfile {
  const slug = authorToReporterSlugMap[authorName] || 'suresh';
  return reporterProfiles[slug] || reporterProfiles['default'];
}

export function formatTimeAgo(dateStr: string): string {
  const d = new Date(dateStr);
  const hours = d.getHours();
  const mins = String(d.getMinutes()).padStart(2, '0');
  const ampm = hours >= 12 ? 'PM' : 'AM';
  const h = hours % 12 || 12;
  return `${h}:${mins} ${ampm}`;
}
