export interface NewsArticle {
  id: string;
  slug: string;
  title: string;
  description: string;
  content: string;
  category: string;
  categorySlug: string;
  categoryColor: string;
  image: string;
  author: string;
  publishedAt: string;
  isBreaking: boolean;
  isTrending: boolean;
  isFeatured: boolean;
  views: number;
  tags: string[];
  videoUrl?: string;
}

export const categories = [
  { name: 'హోమ్', slug: 'home', color: '#C00000' },
  { name: 'తాజా వార్తలు', slug: 'latest', color: '#C00000' },
  { name: 'ఈ-పేపర్', slug: 'epaper', color: '#0f766e' },
  { name: 'రాజకీయాలు', slug: 'politics', color: '#1a6b3a' },
  { name: 'ఆంధ్రప్రదేశ్', slug: 'andhra-pradesh', color: '#d97706' },
  { name: 'తెలంగాణ', slug: 'telangana', color: '#7c3aed' },
  { name: 'జాతీయ', slug: 'national', color: '#0369a1' },
  { name: 'అంతర్జాతీయ', slug: 'international', color: '#0e7490' },
  { name: 'వ్యాపారం', slug: 'business', color: '#15803d' },
  { name: 'సినిమా', slug: 'entertainment', color: '#db2777' },
  { name: 'క్రీడలు', slug: 'sports', color: '#ea580c' },
  { name: 'టెక్నాలజీ', slug: 'technology', color: '#4f46e5' },
  { name: 'ఆరోగ్యం', slug: 'health', color: '#0891b2' },
  { name: 'వైరల్', slug: 'viral', color: '#dc2626' },
  { name: 'లైఫ్ స్టైల్', slug: 'lifestyle', color: '#9333ea' },
  { name: 'రాశిఫలాలు', slug: 'rasipalalu', color: '#b45309' },
  { name: 'ఆల్బమ్‌లు', slug: 'photos', color: '#64748b' },
  { name: 'వీడియోలు', slug: 'videos', color: '#dc2626' },
];

export const breakingNews: string[] = [
  'ఆంధ్రప్రదేశ్‌లో భారీ వర్షాలు - జిల్లాల్లో అలర్ట్ జారీ',
  'హైదరాబాద్‌లో మెట్రో రైలు విస్తరణకు ప్రభుత్వం ఆమోదం',
  'తెలంగాణ బడ్జెట్ సమావేశాలు రేపటి నుంచి ప్రారంభం',
  'భారత క్రికెట్ జట్టు వన్డే సిరీస్‌లో విజయం - 3-0తో గెలుపు',
  'సెన్సెక్స్ 200 పాయింట్లు పెరిగింది - మార్కెట్లో ర్యాలీ',
  'రాజకీయ నాయకుడు సభలో సంచలన వ్యాఖ్యలు',
  'AI రంగంలో భారత్ అగ్రస్థానానికి చేరుకుంటుందని నిపుణుల అంచనా',
];

export const featuredNews: NewsArticle[] = [
  {
    id: '1',
    slug: 'ap-heavy-rains-alert-2024',
    title: 'ఆంధ్రప్రదేశ్‌లో భారీ వర్షాలు: పలు జిల్లాల్లో రెడ్ అలర్ట్ జారీ చేసిన వాతావరణ శాఖ',
    description: 'రాష్ట్రంలో ముందస్తు రుతుపవనాలు ప్రవేశించిన నేపథ్యంలో తీరప్రాంత జిల్లాలు సహా పలు ప్రాంతాల్లో భారీ వర్షాలు కురుస్తున్నాయి.',
    content: 'ఆంధ్రప్రదేశ్ తీరప్రాంత జిల్లాలలో భారీ వర్షాలు కురుస్తున్న నేపథ్యంలో వాతావరణ శాఖ అలర్ట్ జారీ చేసింది...',
    category: 'ఆంధ్రప్రదేశ్',
    categorySlug: 'andhra-pradesh',
    categoryColor: '#d97706',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=675&fit=crop',
    author: 'హై టీవీ రిపోర్టర్',
    publishedAt: '2024-06-05T08:30:00Z',
    isBreaking: true,
    isTrending: true,
    isFeatured: true,
    views: 45230,
    tags: ['వర్షాలు', 'ఆంధ్రప్రదేశ్', 'అలర్ట్'],
  },
  {
    id: '2',
    slug: 'telangana-metro-expansion',
    title: 'హైదరాబాద్ మెట్రో విస్తరణకు కేంద్ర ప్రభుత్వం ₹18,000 కోట్ల నిధులకు ఆమోదం',
    description: 'హైదరాబాద్ మెట్రో రైలు నెట్‌వర్క్‌ను మరింత విస్తరించేందుకు కేంద్ర ప్రభుత్వం భారీ నిధులు మంజూరు చేసింది.',
    content: 'కేంద్ర మంత్రివర్గం బుధవారం హైదరాబాద్ మెట్రో విస్తరణ ప్రాజెక్ట్‌కు ₹18,000 కోట్ల నిధులకు ఆమోదం తెలిపింది...',
    category: 'తెలంగాణ',
    categorySlug: 'telangana',
    categoryColor: '#7c3aed',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=675&fit=crop',
    author: 'హై టీవీ బ్యూరో',
    publishedAt: '2024-06-05T07:15:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: true,
    views: 32100,
    tags: ['మెట్రో', 'హైదరాబాద్', 'తెలంగాణ'],
  },
  {
    id: '3',
    slug: 'india-cricket-odi-series-win',
    title: 'భారత్ వన్డే సిరీస్ గెలుపు: రోహిత్ నేతృత్వంలో క్లీన్ స్వీప్ - అభిమానులలో సంబురాలు',
    description: 'భారత క్రికెట్ జట్టు మూడు వన్డే మ్యాచ్‌ల సిరీస్‌లో 3-0తో క్లీన్ స్వీప్ సాధించింది.',
    content: 'టీమ్ ఇండియా వన్డే క్రికెట్ సిరీస్‌లో అద్భుతమైన ఆట ప్రదర్శించి...',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=675&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-05T06:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: true,
    views: 67890,
    tags: ['క్రికెట్', 'భారత్', 'వన్డే'],
  },
  {
    id: '4',
    slug: 'sensex-rally-market-high',
    title: 'సెన్సెక్స్ కొత్త రికార్డు స్థాయికి: 200 పాయింట్లు పెరిగి 80,000 అంకె దాటింది',
    description: 'బాంబే స్టాక్ ఎక్స్ఛేంజ్ సూచీ నూతన అత్యధిక స్థాయికి చేరుకుంది. విదేశీ పెట్టుబడులు పెరగడంతో మార్కెట్‌లో జోష్.',
    content: 'దేశీయ స్టాక్ మార్కెట్ సూచీలు బుధవారం భారీగా పెరిగాయి...',
    category: 'వ్యాపారం',
    categorySlug: 'business',
    categoryColor: '#15803d',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=675&fit=crop',
    author: 'ఆర్థిక విభాగం',
    publishedAt: '2024-06-05T05:45:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: true,
    views: 28450,
    tags: ['సెన్సెక్స్', 'మార్కెట్', 'పెట్టుబడులు'],
  },
];

export const politicsNews: NewsArticle[] = [
  {
    id: '10',
    slug: 'ap-cm-budget-announcement',
    title: 'ఆంధ్రప్రదేశ్ ముఖ్యమంత్రి సంచలన ప్రకటన: రైతులకు ₹5,000 కోట్ల ప్యాకేజీ',
    description: 'రాష్ట్ర ప్రభుత్వం రైతు సంక్షేమం కోసం భారీ ఆర్థిక ప్యాకేజీ ప్రకటించింది.',
    content: '',
    category: 'రాజకీయాలు',
    categorySlug: 'politics',
    categoryColor: '#1a6b3a',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=450&fit=crop',
    author: 'రాజకీయ విభాగం',
    publishedAt: '2024-06-05T09:00:00Z',
    isBreaking: true,
    isTrending: false,
    isFeatured: false,
    views: 34500,
    tags: ['రాజకీయాలు', 'ఆంధ్రప్రదేశ్', 'రైతులు'],
  },
  {
    id: '11',
    slug: 'telangana-opposition-press-meet',
    title: 'తెలంగాణలో విపక్ష పార్టీల సంయుక్త సమావేశం - ప్రభుత్వంపై తీవ్ర విమర్శలు',
    description: 'విపక్ష నేతలు ప్రభుత్వ విధానాలను తీవ్రంగా విమర్శిస్తూ పలు ఆరోపణలు చేశారు.',
    content: '',
    category: 'రాజకీయాలు',
    categorySlug: 'politics',
    categoryColor: '#1a6b3a',
    image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=450&fit=crop',
    author: 'రాజకీయ విభాగం',
    publishedAt: '2024-06-05T08:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 21300,
    tags: ['రాజకీయాలు', 'తెలంగాణ', 'విపక్షం'],
  },
  {
    id: '12',
    slug: 'parliament-session-highlights',
    title: 'పార్లమెంట్ సమావేశంలో వేడి చర్చ: విపక్షం వాకౌట్ - సభలో గందరగోళం',
    description: 'కేంద్ర పార్లమెంట్ బడ్జెట్ సమావేశంలో ప్రతిపక్ష సభ్యులు నిరసన తెలిపి వాకౌట్ చేశారు.',
    content: '',
    category: 'జాతీయ',
    categorySlug: 'national',
    categoryColor: '#0369a1',
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&h=450&fit=crop',
    author: 'ఢిల్లీ బ్యూరో',
    publishedAt: '2024-06-05T07:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 18900,
    tags: ['పార్లమెంట్', 'జాతీయ', 'విపక్షం'],
  },
  {
    id: '13',
    slug: 'election-commission-announcement',
    title: 'ఎన్నికల కమిషన్ కీలక నిర్ణయం: ఉప ఎన్నికలకు తేదీలు ప్రకటన',
    description: 'కేంద్ర ఎన్నికల కమిషన్ పలు నియోజకవర్గాలలో జరిగే ఉప ఎన్నికల షెడ్యూలు విడుదల చేసింది.',
    content: '',
    category: 'రాజకీయాలు',
    categorySlug: 'politics',
    categoryColor: '#1a6b3a',
    image: 'https://images.unsplash.com/photo-1494172961521-33799ddd43a5?w=800&h=450&fit=crop',
    author: 'రాజకీయ విభాగం',
    publishedAt: '2024-06-04T14:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 15600,
    tags: ['ఎన్నికలు', 'కమిషన్'],
  },
];

export const entertainmentNews: NewsArticle[] = [
  {
    id: '20',
    slug: 'tollywood-blockbuster-release',
    title: 'టాలీవుడ్ బ్లాక్‌బస్టర్: పెద్ద హీరో కొత్త చిత్రం మొదటి రోజు ₹100 కోట్లు వసూలు',
    description: 'తెలుగు సినీ ప్రేక్షకులు పెద్ద సంఖ్యలో థియేటర్లకు తరలివెళ్ళారు. ట్రేడ్ అనలిస్టులు ఆశ్చర్యం వ్యక్తం.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-05T10:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 89000,
    tags: ['సినిమా', 'టాలీవుడ్', 'బాక్సాఫీస్'],
  },
  {
    id: '21',
    slug: 'actress-award-ceremony',
    title: 'ఫిల్మ్‌ఫేర్ అవార్డ్స్ సందడి: తెలుగు నటీనటులు పలు పురస్కారాలు అందుకున్నారు',
    description: 'ప్రతిష్ఠాత్మక ఫిల్మ్‌ఫేర్ అవార్డ్స్ వేడుకలో తెలుగు చిత్రసీమ తళతళ మెరిసింది.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-04T20:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 54300,
    tags: ['అవార్డులు', 'సినిమా', 'తెలుగు'],
  },
  {
    id: '22',
    slug: 'ott-new-series-release',
    title: 'OTT సంచలనం: నెట్‌ఫ్లిక్స్‌లో తెలుగు వెబ్ సిరీస్ విడుదల - ప్రేక్షకుల మెచ్చుకోలు',
    description: 'తెలుగులో నేరుగా OTT ప్లాట్‌ఫామ్‌పై విడుదలైన వెబ్ సిరీస్ భారీ ఆదరణ పొందుతుంది.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-04T16:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 43200,
    tags: ['OTT', 'వెబ్ సిరీస్', 'నెట్‌ఫ్లిక్స్'],
  },
  {
    id: '23',
    slug: 'hero-new-movie-announcement',
    title: 'సూపర్ స్టార్ కొత్త చిత్రం ప్రకటన: బిగ్ బడ్జెట్ యాక్షన్ థ్రిల్లర్ తయారీ మొదలు',
    description: 'తెలుగు చలనచిత్ర పరిశ్రమలో సంచలనం రేపుతున్న నటుడు కొత్త చిత్రం ప్రారంభోత్సవం.',
    content: '',
    category: 'సినిమా',
    categorySlug: 'entertainment',
    categoryColor: '#db2777',
    image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=450&fit=crop',
    author: 'సినిమా విభాగం',
    publishedAt: '2024-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 62100,
    tags: ['సినిమా', 'టాలీవుడ్', 'యాక్షన్'],
  },
];

export const sportsNews: NewsArticle[] = [
  {
    id: '30',
    slug: 'ipl-final-match-report',
    title: 'IPL ఫైనల్ మ్యాచ్: రోమాంచకర పోరాటంలో హైదరాబాద్ జట్టు ఛాంపియన్',
    description: 'ఇండియన్ ప్రీమియర్ లీగ్ ఫైనల్‌లో హైదరాబాద్ జట్టు అద్భుత విజయం సాధించింది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-05T11:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 98500,
    tags: ['IPL', 'క్రికెట్', 'హైదరాబాద్'],
  },
  {
    id: '31',
    slug: 'badminton-world-championship',
    title: 'బ్యాడ్మింటన్ విజయం: భారత ఆటగాడు వరల్డ్ ఛాంపియన్‌షిప్‌లో స్వర్ణం',
    description: 'తెలుగు తేజం బ్యాడ్మింటన్ కోర్ట్‌పై మెరిసి ప్రపంచ ఛాంపియన్ పట్టం నొంది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-04T18:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 45600,
    tags: ['బ్యాడ్మింటన్', 'చాంపియన్', 'భారత్'],
  },
  {
    id: '32',
    slug: 'pro-kabaddi-results',
    title: 'ప్రో కబడ్డీ: తెలుగు టైటాన్స్ అద్భుత గెలుపు - ప్లేఆఫ్స్‌కు అర్హత',
    description: 'ప్రో కబడ్డీ లీగ్‌లో తెలుగు టైటాన్స్ జట్టు ప్లేఆఫ్స్‌కు అర్హత సాధించింది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-04T15:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 32100,
    tags: ['కబడ్డీ', 'తెలుగు టైటాన్స్'],
  },
  {
    id: '33',
    slug: 'football-premier-league',
    title: 'ఫుట్‌బాల్: ప్రీమియర్ లీగ్ టైటిల్ రేసులో మాంచెస్టర్ సిటీ ముందంజ',
    description: 'ఇంగ్లిష్ ప్రీమియర్ లీగ్‌లో టైటిల్ పోటీలో మాంచెస్టర్ సిటీ ముందు నిలిచింది.',
    content: '',
    category: 'క్రీడలు',
    categorySlug: 'sports',
    categoryColor: '#ea580c',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&h=450&fit=crop',
    author: 'క్రీడా విభాగం',
    publishedAt: '2024-06-04T10:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 24300,
    tags: ['ఫుట్‌బాల్', 'ప్రీమియర్ లీగ్'],
  },
];

export const technologyNews: NewsArticle[] = [
  {
    id: '40',
    slug: 'ai-revolution-india',
    title: 'AI విప్లవం: భారత్‌లో కృత్రిమ మేధ స్టార్టప్‌లు ₹50,000 కోట్ల పెట్టుబడులు ఆకర్షించాయి',
    description: 'కృత్రిమ మేధ రంగంలో భారతీయ స్టార్టప్‌లు అంతర్జాతీయ పెట్టుబడిదారులను ఆకర్షిస్తున్నాయి.',
    content: '',
    category: 'టెక్నాలజీ',
    categorySlug: 'technology',
    categoryColor: '#4f46e5',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=450&fit=crop',
    author: 'టెక్ విభాగం',
    publishedAt: '2024-06-05T09:30:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 38900,
    tags: ['AI', 'స్టార్టప్', 'భారత్'],
  },
  {
    id: '41',
    slug: 'smartphone-new-launch',
    title: 'స్మార్ట్‌ఫోన్ విప్లవం: సాంసంగ్ కొత్త ఫోల్డబుల్ ఫోన్ భారత మార్కెట్లో లాంచ్',
    description: 'సాంసంగ్ తాజా ఫోల్డబుల్ స్మార్ట్‌ఫోన్ భారత్‌లో అందుబాటులోకి వచ్చింది.',
    content: '',
    category: 'టెక్నాలజీ',
    categorySlug: 'technology',
    categoryColor: '#4f46e5',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=450&fit=crop',
    author: 'టెక్ విభాగం',
    publishedAt: '2024-06-04T14:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 29700,
    tags: ['స్మార్ట్‌ఫోన్', 'సాంసంగ్', 'మొబైల్'],
  },
];

export const businessNews: NewsArticle[] = [
  {
    id: '50',
    slug: 'rbi-repo-rate-decision',
    title: 'RBI కీలక నిర్ణయం: రెపో రేట్ మార్పు లేదు - ద్రవ్యోల్బణం నియంత్రణపై దృష్టి',
    description: 'రిజర్వ్ బ్యాంక్ ఆఫ్ ఇండియా వడ్డీ రేట్లను యథాతథంగా కొనసాగించాలని నిర్ణయించింది.',
    content: '',
    category: 'వ్యాపారం',
    categorySlug: 'business',
    categoryColor: '#15803d',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop',
    author: 'ఆర్థిక విభాగం',
    publishedAt: '2024-06-05T10:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 22400,
    tags: ['RBI', 'వడ్డీ రేట్లు', 'ఆర్థికం'],
  },
  {
    id: '51',
    slug: 'real-estate-boom-hyderabad',
    title: 'హైదరాబాద్‌లో రియల్ ఎస్టేట్ బూమ్: అపార్ట్‌మెంట్ ధరలు 30% పెరుగుదల',
    description: 'IT హబ్ హైదరాబాద్‌లో రియల్ ఎస్టేట్ మార్కెట్ జోరందుకుంది. ఫ్లాట్ ధరలు భారీగా పెరుగుతున్నాయి.',
    content: '',
    category: 'వ్యాపారం',
    categorySlug: 'business',
    categoryColor: '#15803d',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=450&fit=crop',
    author: 'ఆర్థిక విభాగం',
    publishedAt: '2024-06-04T16:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 31200,
    tags: ['రియల్ ఎస్టేట్', 'హైదరాబాద్'],
  },
];

export const healthNews: NewsArticle[] = [
  {
    id: '60',
    slug: 'monsoon-diseases-prevention',
    title: 'వర్షాకాలంలో జాగ్రత్తలు: డెంగీ, మలేరియా నివారణకు ఆరోగ్య శాఖ సూచనలు',
    description: 'రుతుపవనాల సీజన్‌లో సాధారణంగా వ్యాప్తి చెందే వ్యాధుల నివారణకు ఆరోగ్య శాఖ గైడ్‌లైన్స్ జారీ.',
    content: '',
    category: 'ఆరోగ్యం',
    categorySlug: 'health',
    categoryColor: '#0891b2',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=450&fit=crop',
    author: 'ఆరోగ్య విభాగం',
    publishedAt: '2024-06-05T08:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 18700,
    tags: ['ఆరోగ్యం', 'వర్షాకాలం', 'వ్యాధులు'],
  },
];

export const viralNews: NewsArticle[] = [
  {
    id: '70',
    slug: 'viral-video-dog-saves-child',
    title: 'వైరల్ వీడియో: నీటిలో మునిగిపోతున్న పిల్లవాడిని కుక్క రక్షించిన వీడియో నెట్‌లో సంచలనం',
    description: 'ఒక చిన్న పిల్లవాడిని కాపాడిన కుక్క వీడియో సోషల్ మీడియాలో వైరల్ అయింది.',
    content: '',
    category: 'వైరల్',
    categorySlug: 'viral',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=450&fit=crop',
    author: 'డిజిటల్ విభాగం',
    publishedAt: '2024-06-05T07:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 125000,
    tags: ['వైరల్', 'వీడియో', 'సోషల్ మీడియా'],
  },
];

export const videoNews: NewsArticle[] = [
  {
    id: '80',
    slug: 'video-ap-floods-coverage',
    title: 'ఆంధ్రప్రదేశ్ వరదలు: భారీ నీటి ప్రవాహం వీడియో - ప్రభావిత ప్రాంతాల దృశ్యాలు',
    description: 'AP వరదలపై ప్రత్యేక వీడియో కవరేజ్.',
    content: '',
    category: 'వీడియోలు',
    categorySlug: 'videos',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop',
    author: 'వీడియో విభాగం',
    publishedAt: '2024-06-05T09:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 56000,
    tags: ['వీడియో', 'వరదలు'],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: '81',
    slug: 'video-cricket-highlights',
    title: 'క్రికెట్ హైలైట్స్: భారత్ vs ఆస్ట్రేలియా మ్యాచ్ అత్యుత్తమ క్షణాలు',
    description: 'మ్యాచ్ హైలైట్స్ వీడియో కవరేజ్.',
    content: '',
    category: 'వీడియోలు',
    categorySlug: 'videos',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&h=450&fit=crop',
    author: 'వీడియో విభాగం',
    publishedAt: '2024-06-04T20:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 87000,
    tags: ['క్రికెట్', 'వీడియో'],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: '82',
    slug: 'video-budget-analysis',
    title: 'బడ్జెట్ విశ్లేషణ: నిపుణులు చెప్పే అంశాలు - నేరుగా మీకు',
    description: 'బడ్జెట్ ప్రతిపాదనలపై నిపుణుల విశ్లేషణ.',
    content: '',
    category: 'వీడియోలు',
    categorySlug: 'videos',
    categoryColor: '#dc2626',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop',
    author: 'వీడియో విభాగం',
    publishedAt: '2024-06-04T16:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 43200,
    tags: ['బడ్జెట్', 'వీడియో', 'విశ్లేషణ'],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
];

export const rasipalaluNews: NewsArticle[] = [
  {
    id: '90',
    slug: 'daily-horoscope-june-5-2026',
    title: 'నేటి రాశిఫలాలు: జూన్ 5, 2026 నాటి ద్వాదశ రాశిఫలాలు.. ఈ రాశి వారికి ఆకస్మిక ధనలాభం!',
    description: 'నేటి రోజు మీ రాశి ఫలాలు ఎలా ఉన్నాయి? ఏ రాశి వారికి అనుకూలంగా ఉంది? ఏ రాశి వారు అప్రమత్తంగా ఉండాలో ఇక్కడ తెలుసుకోండి.',
    content: 'నేటి రోజు మీ రాశి ఫలాలు ఎలా ఉన్నాయి? మేష రాశి నుండి మీన రాశి వరకు గల ద్వాదశ రాశుల ఫలితాలు ఇక్కడ తెలుసుకోండి. మేష రాశి: అనుకూల సమయం, ఉద్యోగంలో పురోగతి ఉంటుంది. వృషభ రాశి: ప్రయాణాల్లో జాగ్రత్త అవసరం. మిథున రాశి: ఆకస్మిక ధనలాభం కలిగే అవకాశం ఉంది. కర్కాటక రాశి: కుటుంబ సభ్యులతో ఆనందంగా గడుపుతారు. సింహ రాశి: వ్యాపారంలో లాభాలు వస్తాయి. కన్యా రాశి: ఆరోగ్యంపై శ్రద్ధ వహించండి. తులా రాశి: నూతన పనులు ప్రారంభిస్తారు. వృశ్చిక రాశి: ఖర్చులు పెరుగుతాయి. ధనుస్సు రాశి: పనులన్నీ సజావుగా సాగుతాయి. మకర రాశి: గౌరవ ప్రతిష్టలు పెరుగుతాయి. కుంభ రాశి: శుభవార్తలు వింటారు. మీన రాశి: మిశ్రమ ఫలితాలు ఉంటాయి.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=450&fit=crop',
    author: 'హై టీవీ భక్తి విభాగం',
    publishedAt: '2026-06-05T06:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 15400,
    tags: ['రాశిఫలాలు', 'నేటి రాశిఫలాలు', 'జ్యోతిష్యం', 'భక్తి'],
  },
  {
    id: '91',
    slug: 'weekly-horoscope-june-5-to-11',
    title: 'వారఫలాలు: జూన్ 5 నుంచి జూన్ 11 వరకు.. ఈ రాశుల వారికి ఉద్యోగంలో ప్రమోషన్!',
    description: 'ఈ వారంలో ద్వాదశ రాశుల వారి జాతకం ఎలా ఉండబోతోంది? ఎవరికి కెరీర్ మెరుగ్గా ఉంటుంది? ఆరోగ్య విషయాల్లో ఎలాంటి జాగ్రత్తలు తీసుకోవాలి?',
    content: 'ఈ వారం ద్వాదశ రాశుల వారి భవిష్యత్తు ఎలా ఉండబోతోందంటే... మేష రాశి వారికి ఉద్యోగంలో అనుకూలమైన మార్పులు ఉంటాయి, ప్రమోషన్ లభించే అవకాశం ఉంది. వృషభ రాశి వారు ఆర్థిక విషయాల్లో జాగ్రత్తగా ఉండాలి. మిథున రాశి విద్యార్థులు విజయం సాధిస్తారు. కర్కాటక రాశి వారికి గృహ నిర్మాణ పనులు వేగవంతం అవుతాయి. సింహ రాశి వారికి వ్యాపార విస్తరణకు అనుకూలం. కన్యా రాశి వారు వివాదాలకు దూరంగా ఉండాలి. తులా రాశి ఉద్యోగస్తులకు ప్రశంసలు దక్కుతాయి. వృశ్చిక రాశి వారికి ప్రయాణాల వల్ల ప్రయోజనం. ధనుస్సు రాశి వారు ఆరోగ్యాన్ని నిర్లక్ష్యం చేయవద్దు. మకర రాశి వారికి ఆశించిన అవకాశాలు వస్తాయి. కుంభ రాశి వారు శుభకార్యాల్లో పాల్గొంటారు. మీన రాశి వారికి పనులు విజయవంతంగా పూర్తవుతాయి.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1532960401447-7dd05bef20b0?w=800&h=450&fit=crop',
    author: 'ఆచార్య కృష్ణప్రసాద్',
    publishedAt: '2026-06-05T05:30:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 22800,
    tags: ['వారఫలాలు', 'రాశిఫలాలు', 'జాతకం', 'గ్రహాలు'],
  },
  {
    id: '92',
    slug: 'yearly-horoscope-forecast-2026',
    title: 'సంవత్సర రాశిఫలాలు 2026: మీ రాశికి ఈ సంవత్సరం ఎలాంటి ఫలితాలు రాబోతున్నాయి?',
    description: 'నూతన సంవత్సరంలో ద్వాదశ రాశుల వారి గ్రహాల సంచారం ఆధారంగా కెరీర్, పెళ్లి, కుటుంబం మరియు ఆర్థిక స్థితిగతుల విశ్లేషణ.',
    content: '2026 సంవత్సరంలో గురు, శని, రాహు-కేతువుల సంచారం వల్ల ద్వాదశ రాశుల వారికి విభిన్న ఫలితాలు రాబోతున్నాయి. మేష, సింహ, ధనుస్సు రాశుల వారికి ఈ సంవత్సరం అద్భుతమైన కెరీర్ ఎదుగుదల మరియు ఆర్థిక స్థిరత్వం ఉంటుంది. వృషభ, కన్య, మకర రాశుల వారికి మధ్యస్థ ఫలితాలు ఉంటాయి. మిథున, తుల, కుంభ రాశుల వారు ఆరోగ్య విషయాల్లో అప్రమత్తంగా ఉండాలి. కర్కాటక, వృశ్చిక, మీన రాశుల వారికి సామాజికంగా గౌరవ ప్రతిష్టలు లభిస్తాయి.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=800&h=450&fit=crop',
    author: 'సిద్ధాంతి సుబ్రహ్మణ్య శర్మ',
    publishedAt: '2026-06-04T18:00:00Z',
    isBreaking: false,
    isTrending: true,
    isFeatured: false,
    views: 41200,
    tags: ['సంవత్సర ఫలాలు', 'రాశిఫలాలు', '2026 జాతకం'],
  },
  {
    id: '93',
    slug: 'saturn-transit-effects-and-remedies-2026',
    title: 'శని గోచారం 2026: శని దేవుడి సంచారం వల్ల ఈ మూడు రాశుల వారికి విపరీతమైన రాజయోగం!',
    description: 'కుంభ రాశిలో శని సంచారం వల్ల ఏ రాశుల వారికి సానుకూల ఫలితాలు వస్తాయి? ఎలాంటి పరిహారాలు చేయాలో పూర్తి వివరాలు.',
    content: 'శని దేవుడు స్వక్షేత్రమైన కుంభ రాశిలో సంచరించడం వల్ల కొన్ని రాశుల వారికి శశ మహాపురుష యోగం పడుతోంది. దీనివల్ల మేషం, మిథునం, మరియు తులా రాశుల వారికి అపారమైన కీర్తి, సంపద దక్కుతాయి. శని ప్రభావం వల్ల ఏదైనా ఆటంకాలు ఎదురైతే శనివారం నాడు నువ్వుల నూనెతో దీపారాధన చేయడం, హనుమాన్ చాలీసా పఠించడం ద్వారా ఉపశమనం లభిస్తుంది.',
    category: 'రాశిఫలాలు',
    categorySlug: 'rasipalalu',
    categoryColor: '#b45309',
    image: 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=800&h=450&fit=crop',
    author: 'హై టీవీ భక్తి విభాగం',
    publishedAt: '2026-06-04T12:00:00Z',
    isBreaking: false,
    isTrending: false,
    isFeatured: false,
    views: 35000,
    tags: ['శని దేవుడు', 'శని గోచారం', 'జ్యోతిష్యం'],
  },
];

export const galleryImages = [
  { id: 1, src: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=600&h=400&fit=crop', alt: 'రాజకీయ సభ' },
  { id: 2, src: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&h=800&fit=crop', alt: 'క్రికెట్ మ్యాచ్' },
  { id: 3, src: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop', alt: 'వరదలు' },
  { id: 4, src: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&h=600&fit=crop', alt: 'హైదరాబాద్ నగరం' },
  { id: 5, src: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&h=400&fit=crop', alt: 'సినిమా వేడుక' },
  { id: 6, src: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=800&fit=crop', alt: 'స్టాక్ మార్కెట్' },
];

export function formatTimeAgo(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);

  if (diffMins < 1) return 'ఇప్పుడే';
  if (diffMins < 60) return `${diffMins} నిమిషాల క్రితం`;
  if (diffHours < 24) return `${diffHours} గంటల క్రితం`;
  return `${diffDays} రోజుల క్రితం`;
}
